// deck.ts —— 右侧工作台检视 Deck (Diffs/Terminal/Jobs/Files)
import { tags, each, h } from "./dom";
import {
  deckTab,
  setDeckTab,
  deckOpen,
  toggleDeck,
  diffs,
  activeDiffPath,
  activeDiffFile,
  totalDiffStats,
  terminalLines,
  jobs,
  files,
  loadFiles,
  appendTerminalLine,
} from "./store";
import { ansiToHtml } from "./term";
import { DeckTab, FileDiff, JobItem, TerminalLine, FileTreeItem } from "./types";
import { signal, effect } from "./signal";
import { apiFetch } from "./net";

export function renderDeck(): HTMLElement {
  return tags.aside(
    {
      class: () => `workbench-deck ${deckOpen() ? "is-open" : "is-closed"}`,
    },
    // Deck 顶栏选项卡
    tags.header(
      { class: "deck-header" },
      tags.div(
        { class: "deck-tabs" },
        renderDeckTabBtn("diffs", "Diffs", () => {
          const st = totalDiffStats();
          return st.files > 0 ? `${st.files}` : "";
        }),
        renderDeckTabBtn("terminal", "Terminal", () => {
          const len = terminalLines().length;
          return len > 0 ? `${len}` : "";
        }),
        renderDeckTabBtn("jobs", "Jobs", () => {
          const runCount = jobs().filter((j) => j.status === "running").length;
          return runCount > 0 ? `${runCount}` : "";
        }),
        renderDeckTabBtn("files", "Files")
      ),
      tags.div(
        { class: "deck-header-actions" },
        tags.button(
          {
            class: "deck-close-btn",
            title: "Close Deck (Ctrl+J)",
            onclick: toggleDeck,
          },
          "✕"
        )
      )
    ),

    // Deck 主体内容区（根据 deckTab 响应式切换）
    tags.div(
      { class: "deck-body" },
      () => {
        const current = deckTab();
        switch (current) {
          case "diffs":
            return renderDiffsPanel();
          case "terminal":
            return renderTerminalPanel();
          case "jobs":
            return renderJobsPanel();
          case "files":
            return renderFilesPanel();
        }
      }
    )
  );
}

function renderDeckTabBtn(tab: DeckTab, title: string, badgeFn?: () => string): HTMLElement {
  return tags.button(
    {
      class: () => `deck-tab-btn ${deckTab() === tab ? "is-active" : ""}`,
      onclick: () => setDeckTab(tab),
    },
    tags.span({}, title),
    () => {
      const badge = badgeFn ? badgeFn() : "";
      if (!badge) return null;
      return tags.span({ class: "deck-tab-badge" }, badge);
    }
  );
}

// 1. Diffs 面板
function renderDiffsPanel(): HTMLElement {
  const list = diffs();
  const active = activeDiffFile();
  const stats = totalDiffStats();

  if (list.length === 0) {
    return tags.div(
      { class: "deck-empty" },
      tags.div({ class: "deck-empty-icon" }, "⌥"),
      tags.div({ class: "deck-empty-title" }, "No Changeset Detected"),
      tags.div({ class: "deck-empty-desc" }, "File modifications generated by agent will stream here in real time.")
    );
  }

  return tags.div(
    { class: "diff-panel" },
    // 变更文件选择条
    tags.div(
      { class: "diff-toolbar" },
      tags.div(
        { class: "diff-stats" },
        tags.span({ class: "diff-stat-add" }, `+${stats.additions}`),
        tags.span({ class: "diff-stat-del" }, `-${stats.deletions}`),
        tags.span({ class: "diff-stat-files" }, `${stats.files} files`)
      ),
      tags.div(
        { class: "diff-file-tabs" },
        list.map((file) =>
          tags.button(
            {
              class: () =>
                `diff-file-btn ${active && active.path === file.path ? "is-active" : ""}`,
              onclick: () => activeDiffPath.set(file.path),
            },
            tags.span({ class: `diff-status-pill status-${file.status}` }, file.status[0].toUpperCase()),
            tags.span({ class: "diff-tab-path" }, file.path),
            tags.span({ class: "diff-tab-delta" }, `+${file.additions} -${file.deletions}`)
          )
        )
      )
    ),

    // 当前选中的 Diff 视窗
    tags.div(
      { class: "diff-viewport" },
      active
        ? tags.div(
            { class: "diff-file-view" },
            tags.div(
              { class: "diff-hunk-list" },
              active.hunks.map((hunk) =>
                tags.div(
                  { class: "diff-hunk" },
                  tags.div({ class: "diff-hunk-header" }, hunk.header),
                  tags.div(
                    { class: "diff-lines" },
                    hunk.lines.map((line) =>
                      tags.div(
                        { class: `diff-line line-${line.type}` },
                        tags.span({ class: "diff-line-old" }, line.oldNo ? String(line.oldNo) : ""),
                        tags.span({ class: "diff-line-new" }, line.newNo ? String(line.newNo) : ""),
                        tags.span({ class: "diff-line-marker" }, line.type === "add" ? "+" : line.type === "del" ? "-" : " "),
                        tags.span({ class: "diff-line-content" }, line.content)
                      )
                    )
                  )
                )
              )
            )
          )
        : null
    )
  );
}

// 2. Terminal 面板
function renderTerminalPanel(): HTMLElement {
  const autoScroll = signal<boolean>(true);
  let termEl: HTMLElement | null = null;

  effect(() => {
    terminalLines();
    if (autoScroll() && termEl) {
      setTimeout(() => {
        if (termEl) termEl.scrollTop = termEl.scrollHeight;
      }, 10);
    }
  });

  return tags.div(
    { class: "terminal-panel" },
    // 终端控制条
    tags.div(
      { class: "terminal-bar" },
      tags.div({ class: "terminal-bar-title" }, "Agent Output Terminal"),
      tags.div(
        { class: "terminal-bar-actions" },
        tags.button(
          {
            class: () => `term-act-btn ${autoScroll() ? "is-active" : ""}`,
            title: "Toggle Auto Scroll",
            onclick: () => autoScroll.set(!autoScroll()),
          },
          "Auto-scroll"
        ),
        tags.button(
          {
            class: "term-act-btn",
            title: "Clear output",
            onclick: () => terminalLines.set([]),
          },
          "Clear"
        ),
        tags.button(
          {
            class: "term-act-btn",
            title: "Copy all output",
            onclick: () => {
              const full = terminalLines().map((l) => l.text).join("\n");
              navigator.clipboard.writeText(full);
            },
          },
          "Copy"
        )
      )
    ),

    // 终端输出流
    tags.div(
      {
        class: "terminal-screen",
        ref: (el: HTMLElement) => {
          termEl = el;
        },
      },
      each(terminalLines, (line: TerminalLine) => {
        const row = tags.div({ class: `term-row row-${line.type}` });
        row.innerHTML = `<span class="term-time">${line.time}</span> <span class="term-text">${ansiToHtml(line.text)}</span>`;
        return row;
      }),
      () => {
        if (terminalLines().length === 0) {
          return tags.div({ class: "term-empty" }, "Terminal idle. Commands and logs will stream here.");
        }
        return null;
      }
    )
  );
}

// 3. Jobs 面板
function renderJobsPanel(): HTMLElement {
  const list = jobs();

  if (list.length === 0) {
    return tags.div(
      { class: "deck-empty" },
      tags.div({ class: "deck-empty-icon" }, "⚙"),
      tags.div({ class: "deck-empty-title" }, "No Active Subagent Jobs"),
      tags.div({ class: "deck-empty-desc" }, "Concurrent tasks, background workers, and subagent trees appear here.")
    );
  }

  return tags.div(
    { class: "jobs-panel" },
    each(jobs, (job: JobItem) =>
      tags.div(
        { class: `job-card status-${job.status}` },
        tags.div(
          { class: "job-card-hdr" },
          tags.span({ class: "job-status-dot" }),
          tags.span({ class: "job-name" }, job.name),
          job.role ? tags.span({ class: "job-role" }, job.role) : null,
          tags.span({ class: "job-status-pill" }, job.status.toUpperCase())
        ),
        job.summary
          ? tags.div({ class: "job-summary" }, job.summary)
          : null
      )
    )
  );
}

// 4. Files 面板
function renderFilesPanel(): HTMLElement {
  const filter = signal<string>("");
  const selectedFile = signal<{ path: string; text: string } | null>(null);

  const filtered = () => {
    const q = filter().toLowerCase().trim();
    const list = files();
    if (!q) return list;
    return list.filter((f) => f.path.toLowerCase().includes(q));
  };

  return tags.div(
    { class: "files-panel" },
    // 检索条
    tags.div(
      { class: "files-search-bar" },
      tags.input({
        class: "files-search-input",
        placeholder: "Search workspace files...",
        value: () => filter(),
        oninput: (e: Event) => filter.set((e.target as HTMLInputElement).value),
      }),
      tags.button(
        {
          class: "files-refresh-btn",
          title: "Refresh files",
          onclick: () => loadFiles(),
        },
        "⟳"
      )
    ),

    // 文件列表与预览
    tags.div(
      { class: "files-split" },
      tags.div(
        { class: "files-tree" },
        each(filtered, (item: FileTreeItem) =>
          tags.div(
            {
              class: () =>
                `file-tree-item ${item.dir ? "is-dir" : "is-file"} ${selectedFile() && selectedFile()!.path === item.path ? "is-active" : ""}`,
              onclick: async () => {
                if (item.dir) return;
                try {
                  const res = await apiFetch(`/api/file?path=${encodeURIComponent(item.path)}`);
                  if (res && res.text != null) {
                    selectedFile.set({ path: item.path, text: res.text });
                  }
                } catch (e) {
                  console.error(e);
                }
              },
            },
            tags.span({ class: "item-icon" }, item.dir ? "📁" : "📄"),
            tags.span({ class: "item-name" }, item.name)
          )
        )
      ),
      // 文件预览
      tags.div(
        { class: "file-preview-wrap" },
        () => {
          const cur = selectedFile();
          if (!cur) {
            return tags.div({ class: "file-preview-empty" }, "Select a file to inspect content.");
          }
          return tags.div(
            { class: "file-preview" },
            tags.div({ class: "file-preview-hdr" }, cur.path),
            tags.pre({ class: "file-preview-code" }, cur.text)
          );
        }
      )
    )
  );
}
