//! build_web.zig —— webui TS 构建管线:`piz build-web [src_dir] [out]`。
//!
//! 入口 src/webui/main.ts,顺相对 import(`from "./x"` / `import "./x"`)DFS 拓扑排,
//! 每模块过 sucrase(typescript+imports 双变换 → CJS),外套迷你 require 运行头拼合,
//! 产单文件 src/webui.js(webui.zig @embedFile 不变)。
//!
//! 模块键 = 相对径去 "./" 去 ".ts"(扁平同目)。运行时 require 容忍 "./" 前缀。
//! 循环 import 报错;动态 import() 不支持(无此需求)。

const std = @import("std");
const util = @import("core").util;
const jsrt = @import("core").jsrt;

const MAX_MODULE_BYTES = 2 << 20;
const MAX_MODULES = 128;

const Mod = struct {
    name: []const u8,
    src: []const u8,
};

const Visit = enum { visiting, done };

const prelude =
    \\// <generated by piz build-web —— 勿手改;源在 src/webui/*.ts,改后跑 zig build web>
    \\var __modules = {}, __cache = {};
    \\function __req(n) {
    \\  if (n[0] === "." && n[1] === "/") n = n.slice(2);
    \\  var m = __cache[n];
    \\  if (m) return m.exports;
    \\  if (!__modules[n]) throw new Error("build-web: unknown module " + n);
    \\  m = { exports: {} };
    \\  __cache[n] = m;
    \\  __modules[n](m, m.exports, __req);
    \\  return m.exports;
    \\}
    \\
;

/// 扫源里的相对 import 名(去 "./" 去 ".ts")。从宽:认 `from "./x"` 与 `import "./x"`。
fn scanDeps(a: std.mem.Allocator, src: []const u8, out: *std.ArrayList([]const u8)) !void {
    var i: usize = 0;
    while (i + 8 < src.len) : (i += 1) {
        if (src[i] == '"' or src[i] == '\'') {
            // 由引号反看前缀:from "<sp> 或 import "<sp>(sucrase 前的源,单双引号皆容)
            if (i < 7) continue;
            const pre = src[0..i];
            if (endsWithWord(pre, "from ") or endsWithWord(pre, "import ")) {
                // 前缀合法,引号内即 specifier
            } else continue;
            var j = i + 1;
            const start = j;
            while (j < src.len and src[j] != src[i]) : (j += 1) {}
            const spec = src[start..j];
            if (std.mem.startsWith(u8, spec, "./")) {
                var name = spec[2..];
                if (std.mem.endsWith(u8, name, ".ts")) name = name[0 .. name.len - 3];
                if (std.mem.endsWith(u8, name, ".js")) name = name[0 .. name.len - 3];
                try out.append(a, try a.dupe(u8, name));
            }
        }
    }
}

fn endsWithWord(s: []const u8, w: []const u8) bool {
    return s.len >= w.len and std.mem.eql(u8, s[s.len - w.len ..], w);
}

fn collect(
    a: std.mem.Allocator,
    dir: []const u8,
    name: []const u8,
    seen: *std.StringHashMap(Visit),
    order: *std.ArrayList(Mod),
) !void {
    if (seen.get(name)) |st| {
        if (st == .visiting) return error.CircularImport;
        return;
    }
    try seen.put(try a.dupe(u8, name), .visiting);
    const path = try std.fmt.allocPrint(a, "{s}/{s}.ts", .{ dir, name });
    const src = std.Io.Dir.cwd().readFileAlloc(util.io, path, a, .limited(MAX_MODULE_BYTES)) catch {
        std.debug.print("piz build-web: cannot read {s}\n", .{path});
        return error.ModuleReadFailed;
    };
    var deps: std.ArrayList([]const u8) = .empty;
    try scanDeps(a, src, &deps);
    for (deps.items) |d| try collect(a, dir, d, seen, order);
    try seen.put(try a.dupe(u8, name), .done);
    if (order.items.len >= MAX_MODULES) return error.TooManyModules;
    try order.append(a, .{ .name = try a.dupe(u8, name), .src = src });
}

/// 构建主链:收模块 → 拓扑序 → 逐件 transpileModule → 包 CJS 壳 → 拼出写盘。
/// 返回写出字节数。quickjs 不在(-Dquickjs=false)时报错退。
pub fn run(a: std.mem.Allocator, src_dir: []const u8, out_path: []const u8) !usize {
    if (!jsrt.enabled) {
        std.debug.print("piz build-web: quickjs disabled (rebuild without -Dquickjs=false)\n", .{});
        return error.NoQuickjs;
    }
    var seen = std.StringHashMap(Visit).init(a);
    var order: std.ArrayList(Mod) = .empty;
    try collect(a, src_dir, "main", &seen, &order);

    jsrt.init(std.heap.c_allocator);
    defer jsrt.deinit();

    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(a, prelude);
    for (order.items) |m| {
        const code = jsrt.transpileModule(a, m.src) orelse {
            std.debug.print("piz build-web: ts strip failed in {s}.ts\n", .{m.name});
            return error.TsStripFailed;
        };
        try buf.appendSlice(a, "__modules[\"");
        try buf.appendSlice(a, m.name);
        try buf.appendSlice(a, "\"] = function(module, exports, require) {\n");
        try buf.appendSlice(a, code);
        try buf.appendSlice(a, "\n};\n");
    }
    try buf.appendSlice(a, "__req(\"main\");\n");

    if (std.fs.path.dirname(out_path)) |d| std.Io.Dir.cwd().createDirPath(util.io, d) catch {};
    try std.Io.Dir.cwd().writeFile(util.io, .{ .sub_path = out_path, .data = buf.items });
    return buf.items.len;
}

test "scanDeps 认 from/import 双形,剔外 specifier" {
    const t = std.testing;
    var arena = util.Arena.init(t.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const src =
        \\import { a } from "./util";
        \\import "./side";
        \\import x from "left-pad";
        \\const u = require("./cjs");
        \\export { b } from './render.ts';
    ;
    var out: std.ArrayList([]const u8) = .empty;
    try scanDeps(a, src, &out);
    // require 不认(非 ESM 静态),left-pad 非相对不认
    try t.expectEqual(@as(usize, 3), out.items.len);
    try t.expectEqualStrings("util", out.items[0]);
    try t.expectEqualStrings("side", out.items[1]);
    try t.expectEqualStrings("render", out.items[2]);
}

test "collect 拓扑:依赖先于引用者,环则报" {
    const t = std.testing;
    try util.testInit();
    var arena = util.Arena.init(t.allocator);
    defer arena.deinit();
    const a = arena.allocator();
    const dir = try std.fmt.allocPrint(a, "/tmp/piz_bw_{d}", .{std.os.linux.getpid()});
    defer std.Io.Dir.cwd().deleteTree(util.io, dir) catch {};
    try std.Io.Dir.cwd().createDirPath(util.io, dir);
    try std.Io.Dir.cwd().writeFile(util.io, .{ .sub_path = try std.fmt.allocPrint(a, "{s}/util.ts", .{dir}), .data = "export const x = 1;" });
    try std.Io.Dir.cwd().writeFile(util.io, .{ .sub_path = try std.fmt.allocPrint(a, "{s}/md.ts", .{dir}), .data = "import { x } from \"./util\";\nexport const y = x + 1;" });
    try std.Io.Dir.cwd().writeFile(util.io, .{ .sub_path = try std.fmt.allocPrint(a, "{s}/main.ts", .{dir}), .data = "import { y } from \"./md\";\nconsole.log(y);" });
    var seen = std.StringHashMap(Visit).init(a);
    var order: std.ArrayList(Mod) = .empty;
    try collect(a, dir, "main", &seen, &order);
    try t.expectEqual(@as(usize, 3), order.items.len);
    try t.expectEqualStrings("util", order.items[0].name);
    try t.expectEqualStrings("md", order.items[1].name);
    try t.expectEqualStrings("main", order.items[2].name);
    // 环:util → main → util
    try std.Io.Dir.cwd().writeFile(util.io, .{ .sub_path = try std.fmt.allocPrint(a, "{s}/util.ts", .{dir}), .data = "import \"./main\";" });
    var seen2 = std.StringHashMap(Visit).init(a);
    var order2: std.ArrayList(Mod) = .empty;
    try t.expectError(error.CircularImport, collect(a, dir, "main", &seen2, &order2));
}
