// <generated by piz build-web —— 勿手改;源在 src/webui/*.ts,改后跑 zig build web>
var __modules = {}, __cache = {};
function __req(n) {
  if (n[0] === "." && n[1] === "/") n = n.slice(2);
  var m = __cache[n];
  if (m) return m.exports;
  if (!__modules[n]) throw new Error("build-web: unknown module " + n);
  m = { exports: {} };
  __cache[n] = m;
  __modules[n](m, m.exports, __req);
  return m.exports;
}
__modules["signal"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// signal.ts —— 微型细粒度响应式内核 (Zero-dependency Signals)
// 支持依赖自动追踪、惰性计算、批量合并与自动解除订阅。



let activeEffect = null;
let batchDepth = 0;
const pendingEffects = new Set();















 function signal(initialValue) {
  let value = initialValue;
  const subscribers = new Set();

  function read() {
    if (activeEffect) {
      subscribers.add(activeEffect);
    }
    return value;
  }

  read.get = () => read();

  read.set = (next) => {
    if (Object.is(value, next)) return;
    value = next;
    notify();
  };

  read.update = (fn) => {
    read.set(fn(value));
  };

  read.subscribe = (fn) => {
    return effect(() => {
      fn(read());
    });
  };

  function notify() {
    for (const sub of subscribers) {
      if (batchDepth > 0) {
        pendingEffects.add(sub);
      } else {
        sub();
      }
    }
  }

  return read;
} exports.signal = signal;

 function computed(computeFn) {
  let cachedValue;
  let isDirty = true;
  const subscribers = new Set();

  const runner = () => {
    if (!isDirty) {
      isDirty = true;
      for (const sub of subscribers) {
        if (batchDepth > 0) {
          pendingEffects.add(sub);
        } else {
          sub();
        }
      }
    }
  };

  function read() {
    if (activeEffect) {
      subscribers.add(activeEffect);
    }
    if (isDirty) {
      const prevEffect = activeEffect;
      activeEffect = runner;
      try {
        cachedValue = computeFn();
        isDirty = false;
      } finally {
        activeEffect = prevEffect;
      }
    }
    return cachedValue;
  }

  read.get = () => read();

  read.subscribe = (fn) => {
    return effect(() => {
      fn(read());
    });
  };

  return read;
} exports.computed = computed;

 function effect(fn) {
  let cleanup;
  let isDisposed = false;

  const execute = () => {
    if (isDisposed) return;
    if (cleanup && typeof cleanup === 'function') {
      cleanup();
    }
    const prevEffect = activeEffect;
    activeEffect = execute;
    try {
      cleanup = fn();
    } finally {
      activeEffect = prevEffect;
    }
  };

  execute();

  return () => {
    isDisposed = true;
    if (cleanup && typeof cleanup === 'function') {
      cleanup();
    }
  };
} exports.effect = effect;

 function batch(fn) {
  batchDepth++;
  try {
    return fn();
  } finally {
    batchDepth--;
    if (batchDepth === 0) {
      const toRun = Array.from(pendingEffects);
      pendingEffects.clear();
      for (const sub of toRun) {
        sub();
      }
    }
  }
} exports.batch = batch;

};
__modules["dom"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// dom.ts —— 细粒度响应式声明式 DOM 构造器 (Zero-vdom, Proxy Tags, Exact Reactivity)
var _signal = require('./signal');















 function isSignal(val) {
  return typeof val === "function" && typeof (val ).subscribe === "function";
} exports.isSignal = isSignal;

const SVG_TAGS = new Set([
  "svg", "path", "circle", "rect", "line", "polyline", "polygon", "g", "text"
]);

 function h(
  tag,
  props,
  ...children
) {
  const isSvg = SVG_TAGS.has(tag);
  const el = isSvg
    ? document.createElementNS("http://www.w3.org/2000/svg", tag)
    : document.createElement(tag);

  if (props) {
    for (const [key, value] of Object.entries(props)) {
      if (value == null) continue;

      if (key.startsWith("on") && typeof value === "function") {
        const eventName = key.slice(2).toLowerCase();
        el.addEventListener(eventName, value);
      } else if (key === "class" || key === "className") {
        bindClass(el, value);
      } else if (key === "style") {
        bindStyle(el, value);
      } else if (key === "ref" && typeof value === "function") {
        value(el);
      } else if (typeof value === "function") {
        _signal.effect.call(void 0, () => {
          setAttr(el, key, value());
        });
      } else {
        setAttr(el, key, value);
      }
    }
  }

  appendChildren(el, children);
  return el;
} exports.h = h;

function setAttr(el, key, val) {
  if (val == null || val === false) {
    el.removeAttribute(key);
  } else {
    el.setAttribute(key, val === true ? "" : String(val));
    if (key === "value" && (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement)) {
      el.value = String(val);
    }
  }
}

function bindClass(el, val) {
  if (typeof val === "function") {
    _signal.effect.call(void 0, () => {
      applyClass(el, val());
    });
  } else {
    applyClass(el, val);
  }
}

function applyClass(el, val) {
  if (typeof val === "string") {
    el.setAttribute("class", val);
  } else if (Array.isArray(val)) {
    el.setAttribute("class", val.filter(Boolean).join(" "));
  } else if (typeof val === "object" && val !== null) {
    const classes = [];
    for (const [cls, enabled] of Object.entries(val)) {
      if (typeof enabled === "function") {
        _signal.effect.call(void 0, () => {
          el.classList.toggle(cls, Boolean(enabled()));
        });
      } else if (enabled) {
        classes.push(cls);
      }
    }
    if (classes.length) {
      el.setAttribute("class", classes.join(" "));
    } else {
      el.removeAttribute("class");
    }
  }
}

function bindStyle(el, val) {
  if (typeof val === "function") {
    _signal.effect.call(void 0, () => {
      applyStyle(el, val());
    });
  } else {
    applyStyle(el, val);
  }
}

function applyStyle(el, val) {
  if (typeof val === "string") {
    el.setAttribute("style", val);
  } else if (typeof val === "object" && val !== null) {
    for (const [prop, sVal] of Object.entries(val)) {
      if (typeof sVal === "function") {
        _signal.effect.call(void 0, () => {
          (el.style )[prop] = sVal();
        });
      } else {
        (el.style )[prop] = sVal;
      }
    }
  }
}

function appendChildren(parent, children) {
  for (const child of children) {
    if (child == null || child === false) continue;

    if (Array.isArray(child)) {
      appendChildren(parent, child);
    } else if (typeof child === "function") {
      appendDynamicChild(parent, child);
    } else if (child instanceof Node) {
      parent.appendChild(child);
    } else {
      parent.appendChild(document.createTextNode(String(child)));
    }
  }
}

function appendDynamicChild(parent, getter) {
  const startAnchor = document.createComment("dyn-start");
  const endAnchor = document.createComment("dyn-end");
  parent.appendChild(startAnchor);
  parent.appendChild(endAnchor);

  let renderedNodes = [];

  _signal.effect.call(void 0, () => {
    const p = startAnchor.parentNode;
    if (!p) return;

    for (const node of renderedNodes) {
      if (node.parentNode === p) {
        p.removeChild(node);
      }
    }
    renderedNodes = [];

    const val = getter();
    if (val == null || val === false) return;

    if (Array.isArray(val)) {
      for (const item of val) {
        if (item == null || item === false) continue;
        const node = item instanceof Node ? item : document.createTextNode(String(item));
        p.insertBefore(node, endAnchor);
        renderedNodes.push(node);
      }
    } else {
      const node = val instanceof Node ? val : document.createTextNode(String(val));
      p.insertBefore(node, endAnchor);
      renderedNodes.push(node);
    }
  });
}

 function show(
  condition,
  thenFn,
  elseFn
) {
  const fragment = document.createDocumentFragment();
  appendDynamicChild(fragment, () => {
    const cond = typeof condition === "function" ? condition() : condition;
    return cond ? thenFn() : elseFn ? elseFn() : null;
  });
  return fragment;
} exports.show = show;

 function each(
  items,
  renderItem
) {
  const fragment = document.createDocumentFragment();
  appendDynamicChild(fragment, () => {
    const list = typeof items === "function" ? items() : items;
    if (!Array.isArray(list)) return null;
    return list.map((item, i) => renderItem(item, i));
  });
  return fragment;
} exports.each = each;

// 优雅 Proxy tags：自动支持所有 HTML/SVG 标签，杜绝 undefined function
 const tags = new Proxy({} , {
  get: (_, tag) => (p, ...c) => h(tag, p, ...c),
}); exports.tags = tags;

};
__modules["types"] = function(module, exports, require) {
"use strict";// types.ts —— 核心领域实体类型定义











































































































};
__modules["net"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true}); function _optionalChain(ops) { let lastAccessLHS = undefined; let value = ops[0]; let i = 1; while (i < ops.length) { const op = ops[i]; const fn = ops[i + 1]; i += 2; if ((op === 'optionalAccess' || op === 'optionalCall') && value == null) { return undefined; } if (op === 'access' || op === 'optionalAccess') { lastAccessLHS = value; value = fn(value); } else if (op === 'call' || op === 'optionalCall') { value = fn((...args) => value.call(lastAccessLHS, ...args)); lastAccessLHS = undefined; } } return value; }// net.ts —— 高韧性网络层 (Bearer 鉴权、CSRF 防护、fetch+ReadableStream SSE 流)

let authToken = "";

// 初始化读取 token (同时支持 ?token= 与 #token=)
try {
  let qToken = new URLSearchParams(window.location.search).get("token");
  if (!qToken && window.location.hash.includes("token=")) {
    const hashParams = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    qToken = hashParams.get("token");
  }
  if (qToken) {
    authToken = qToken;
    localStorage.setItem("piz.token", authToken);
  } else {
    authToken = localStorage.getItem("piz.token") || "";
  }
} catch (_) {}

 function getToken() {
  return authToken;
} exports.getToken = getToken;

 function setToken(token) {
  authToken = token.trim();
  try {
    if (authToken) {
      localStorage.setItem("piz.token", authToken);
    } else {
      localStorage.removeItem("piz.token");
    }
  } catch (_) {}
} exports.setToken = setToken;

 async function apiFetch(
  path,
  init = {}
) {
  const headers = new Headers(init.headers || {});
  headers.set("X-Requested-With", "piz");
  if (authToken) {
    headers.set("Authorization", `Bearer ${authToken}`);
  }

  const res = await fetch(path, {
    ...init,
    headers,
  });

  if (res.status === 401) {
    window.dispatchEvent(new CustomEvent("piz:unauthorized"));
    throw new Error("Unauthorized");
  }

  if (!res.ok) {
    const txt = await res.text().catch(() => "");
    throw new Error(`HTTP ${res.status}: ${txt}`);
  }

  const cType = res.headers.get("content-type") || "";
  if (cType.includes("application/json")) {
    return (await res.json()) ;
  }
  return (await res.text()) ;
} exports.apiFetch = apiFetch;



// 基于 fetch + ReadableStream 的 SSE 客户端 (EventSource 原生无法带 Authorization 头)
 function connectEventStream(
  onEvent,
  onStateChange
) {
  let isClosed = false;
  let retryCount = 0;
  let abortCtrl = null;
  let timer = null;

  async function startStream() {
    if (isClosed) return;
    onStateChange("connecting");

    abortCtrl = new AbortController();
    const headers = {
      Accept: "text/event-stream",
      "X-Requested-With": "piz",
    };
    if (authToken) {
      headers["Authorization"] = `Bearer ${authToken}`;
    }

    try {
      const res = await fetch("/api/events", {
        headers,
        signal: abortCtrl.signal,
      });

      if (res.status === 401) {
        onStateChange("disconnected");
        window.dispatchEvent(new CustomEvent("piz:unauthorized"));
        return;
      }

      if (!res.ok || !res.body) {
        throw new Error(`SSE stream failed: HTTP ${res.status}`);
      }

      retryCount = 0;
      onStateChange("connected");

      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        let idx;
        while ((idx = buffer.indexOf("\n\n")) !== -1) {
          const chunk = buffer.slice(0, idx);
          buffer = buffer.slice(idx + 2);

          for (const line of chunk.split("\n")) {
            if (!line.startsWith("data: ")) continue;
            const rawData = line.slice(6).trim();
            if (!rawData) continue;

            try {
              const parsed = JSON.parse(rawData);
              if (parsed && parsed.type) {
                onEvent(parsed);
              } else if (parsed) {
                onEvent({ type: "message", data: parsed });
              }
            } catch (err) {
              console.warn("SSE JSON parse err:", err, rawData);
            }
          }
        }
      }
    } catch (err) {
      if (_optionalChain([err, 'optionalAccess', _2 => _2.name]) === "AbortError" || isClosed) return;
      console.warn("SSE connection error:", err);
    }

    if (!isClosed) {
      onStateChange("disconnected");
      const delay = Math.min(1000 * Math.pow(1.5, retryCount), 10000);
      retryCount++;
      timer = setTimeout(startStream, delay);
    }
  }

  startStream();

  return () => {
    isClosed = true;
    if (timer) clearTimeout(timer);
    if (abortCtrl) abortCtrl.abort();
    onStateChange("disconnected");
  };
} exports.connectEventStream = connectEventStream;

};
__modules["diff"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// diff.ts —— Git Unified Diff 解析与行级比对渲染器


 function parseUnifiedDiff(rawDiff) {
  if (!rawDiff || !rawDiff.trim()) return [];

  const files = [];
  const lines = rawDiff.split(/\r?\n/);
  let currentFile = null;
  let currentHunk = null;
  let oldLineNo = 0;
  let newLineNo = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    if (line.startsWith("diff --git ") || line.startsWith("--- ")) {
      // 提取文件名
      let path = "";
      if (line.startsWith("diff --git ")) {
        const parts = line.slice(11).split(" ");
        if (parts.length >= 2) {
          path = parts[1].replace(/^[ab]\//, "");
        }
      } else if (line.startsWith("--- ")) {
        path = line.slice(4).trim().replace(/^[ab]\//, "");
      }

      if (!currentFile || currentFile.path !== path) {
        currentFile = {
          path: path || "unknown",
          status: "modified",
          additions: 0,
          deletions: 0,
          hunks: [],
          raw: line + "\n",
        };
        files.push(currentFile);
        currentHunk = null;
      } else {
        currentFile.raw += line + "\n";
      }
      continue;
    }

    if (line.startsWith("+++ ")) {
      const p = line.slice(4).trim().replace(/^[ab]\//, "");
      if (currentFile) {
        if (p && p !== "/dev/null") currentFile.path = p;
        currentFile.raw += line + "\n";
      }
      continue;
    }

    if (line.startsWith("@@ ")) {
      if (!currentFile) {
        currentFile = {
          path: "diff",
          status: "modified",
          additions: 0,
          deletions: 0,
          hunks: [],
          raw: "",
        };
        files.push(currentFile);
      }
      currentFile.raw += line + "\n";

      // 解析 @@ -a,b +c,d @@
      const match = /@@ -(\d+)(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(line);
      if (match) {
        oldLineNo = parseInt(match[1], 10);
        newLineNo = parseInt(match[2], 10);
      } else {
        oldLineNo = 1;
        newLineNo = 1;
      }

      currentHunk = {
        header: line,
        lines: [],
      };
      currentFile.hunks.push(currentHunk);
      continue;
    }

    if (!currentHunk || !currentFile) {
      if (currentFile) currentFile.raw += line + "\n";
      continue;
    }

    currentFile.raw += line + "\n";

    if (line.startsWith("+")) {
      currentFile.additions++;
      currentHunk.lines.push({
        type: "add",
        content: line.slice(1),
        newNo: newLineNo++,
      });
    } else if (line.startsWith("-")) {
      currentFile.deletions++;
      currentHunk.lines.push({
        type: "del",
        content: line.slice(1),
        oldNo: oldLineNo++,
      });
    } else if (line.startsWith(" ") || line === "") {
      currentHunk.lines.push({
        type: "context",
        content: line.startsWith(" ") ? line.slice(1) : line,
        oldNo: oldLineNo++,
        newNo: newLineNo++,
      });
    }
  }

  // 计算文件状态
  for (const f of files) {
    if (f.deletions === 0 && f.additions > 0) {
      f.status = "added";
    } else if (f.additions === 0 && f.deletions > 0) {
      f.status = "deleted";
    } else {
      f.status = "modified";
    }
  }

  return files;
} exports.parseUnifiedDiff = parseUnifiedDiff;

};
__modules["store"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true}); function _optionalChain(ops) { let lastAccessLHS = undefined; let value = ops[0]; let i = 1; while (i < ops.length) { const op = ops[i]; const fn = ops[i + 1]; i += 2; if ((op === 'optionalAccess' || op === 'optionalCall') && value == null) { return undefined; } if (op === 'access' || op === 'optionalAccess') { lastAccessLHS = value; value = fn(value); } else if (op === 'call' || op === 'optionalCall') { value = fn((...args) => value.call(lastAccessLHS, ...args)); lastAccessLHS = undefined; } } return value; }// store.ts —— 全局响应式状态机
var _signal = require('./signal');












var _net = require('./net');
var _diff = require('./diff');

// 持久化辅助
function getStored(key, fallback) {
  try {
    const v = localStorage.getItem(`piz.${key}`);
    return v != null ? JSON.parse(v) : fallback;
  } catch (_) {
    return fallback;
  }
}

function setStored(key, val) {
  try {
    localStorage.setItem(`piz.${key}`, JSON.stringify(val));
  } catch (_) {}
}

const urlParams = new URLSearchParams(window.location.search);
 const urlWs = urlParams.get("ws") || ""; exports.urlWs = urlWs;
 const wsName = _signal.signal(exports.urlWs || "workspace"); exports.wsName = wsName;
 const branch = _signal.signal(""); exports.branch = branch;
 const changesCount = _signal.signal(0); exports.changesCount = changesCount;

 const activeSession = _signal.signal(urlParams.get("session") || "default"); exports.activeSession = activeSession;
 const sessions = _signal.signal([]); exports.sessions = sessions;
 const turns = _signal.signal([]); exports.turns = turns;
 const isStreaming = _signal.signal(false); exports.isStreaming = isStreaming;
 const streamingTurnId = _signal.signal(null); exports.streamingTurnId = streamingTurnId;

 const theme = _signal.signal(
  getStored("theme", _optionalChain([window, 'access', _2 => _2.matchMedia, 'optionalCall', _3 => _3("(prefers-color-scheme: light)"), 'access', _4 => _4.matches]) ? "light" : "dark")
); exports.theme = theme;

 const connectionStatus = _signal.signal("connecting"); exports.connectionStatus = connectionStatus;

 const mode = _signal.signal(getStored("mode", "yolo")); exports.mode = mode;
 const model = _signal.signal(""); exports.model = model;
 const models = _signal.signal([]); exports.models = models;
 const pct = _signal.signal(0); exports.pct = pct;

 const deckTab = _signal.signal(getStored("deckTab", "diffs")); exports.deckTab = deckTab;
 const deckOpen = _signal.signal(getStored("deckOpen", true)); exports.deckOpen = deckOpen;
 const sidebarOpen = _signal.signal(getStored("sidebarOpen", true)); exports.sidebarOpen = sidebarOpen;

 const diffs = _signal.signal([]); exports.diffs = diffs;
 const activeDiffPath = _signal.signal(""); exports.activeDiffPath = activeDiffPath;
 const terminalLines = _signal.signal([]); exports.terminalLines = terminalLines;
 const jobs = _signal.signal([]); exports.jobs = jobs;
 const files = _signal.signal([]); exports.files = files;

 const pendingApproval = _signal.signal(null); exports.pendingApproval = pendingApproval;
 const showSearchModal = _signal.signal(false); exports.showSearchModal = showSearchModal;
 const showAuthModal = _signal.signal(false); exports.showAuthModal = showAuthModal;
 const showSettingsModal = _signal.signal(false); exports.showSettingsModal = showSettingsModal;

// 统计衍生物
 const totalDiffStats = _signal.computed.call(void 0, () => {
  let add = 0;
  let del = 0;
  for (const d of exports.diffs.call(void 0, )) {
    add += d.additions;
    del += d.deletions;
  }
  return { additions: add, deletions: del, files: exports.diffs.call(void 0, ).length };
}); exports.totalDiffStats = totalDiffStats;

 const activeDiffFile = _signal.computed.call(void 0, () => {
  const curPath = exports.activeDiffPath.call(void 0, );
  const list = exports.diffs.call(void 0, );
  if (!list.length) return null;
  return list.find((d) => d.path === curPath) || list[0];
}); exports.activeDiffFile = activeDiffFile;

// 构建符合后端白名单规则的安全 query string
 function getQuery(extra = {}) {
  const params = new URLSearchParams();
  const s = exports.activeSession.call(void 0, );
  if (s) params.set("session", s);
  // 空 ws 代表当前默认项目，非空时才传递给后端
  if (exports.urlWs) params.set("ws", exports.urlWs);
  for (const [k, v] of Object.entries(extra)) {
    if (v != null && v !== "") params.set(k, v);
  }
  const q = params.toString();
  return q ? `?${q}` : "";
} exports.getQuery = getQuery;

// 主题切换
 function toggleTheme() {
  const next = exports.theme.call(void 0, ) === "dark" ? "light" : "dark";
  exports.theme.set(next);
  setStored("theme", next);
  document.documentElement.setAttribute("data-color-scheme", next);
} exports.toggleTheme = toggleTheme;

// 工作台控制
 function toggleDeck() {
  const next = !exports.deckOpen.call(void 0, );
  exports.deckOpen.set(next);
  setStored("deckOpen", next);
} exports.toggleDeck = toggleDeck;

 function setDeckTab(tab) {
  exports.deckTab.set(tab);
  setStored("deckTab", tab);
  if (!exports.deckOpen.call(void 0, )) {
    exports.deckOpen.set(true);
    setStored("deckOpen", true);
  }
} exports.setDeckTab = setDeckTab;

 function toggleSidebar() {
  const next = !exports.sidebarOpen.call(void 0, );
  exports.sidebarOpen.set(next);
  setStored("sidebarOpen", next);
} exports.toggleSidebar = toggleSidebar;

// 终端行追加
 function appendTerminalLine(text, type = "stdout") {
  const time = new Date().toLocaleTimeString();
  const line = {
    id: `tl_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
    time,
    text,
    type,
  };
  exports.terminalLines.update((prev) => [...prev.slice(-400), line]);
} exports.appendTerminalLine = appendTerminalLine;

// 核心网络同步
 async function loadState() {
  try {
    const data = await _net.apiFetch.call(void 0, `/api/state${getQuery()}`);
    if (data) {
      _signal.batch.call(void 0, () => {
        if (data.model) exports.model.set(data.model);
        if (typeof data.pct === "number") exports.pct.set(data.pct);
        if (data.mode && (data.mode === "yolo" || data.mode === "ask" || data.mode === "plan")) {
          exports.mode.set(data.mode);
        }
        if (data.ws) exports.wsName.set(data.ws);
        if (data.branch) exports.branch.set(data.branch);
        if (typeof data.changes === "number") exports.changesCount.set(data.changes);
      });
    }
  } catch (err) {
    console.warn("loadState error:", err);
  }
} exports.loadState = loadState;

 async function loadModels() {
  try {
    const res = await _net.apiFetch.call(void 0, "/api/models");
    const list = Array.isArray(res) ? res : Array.isArray(_optionalChain([res, 'optionalAccess', _5 => _5.models])) ? res.models : [];
    exports.models.set(list);
  } catch (err) {
    console.warn("loadModels error:", err);
  }
} exports.loadModels = loadModels;

 async function loadSessions() {
  try {
    const res = await _net.apiFetch.call(void 0, `/api/sessions${getQuery()}`);
    const list = Array.isArray(res) ? res : Array.isArray(_optionalChain([res, 'optionalAccess', _6 => _6.sessions])) ? res.sessions : [];
    exports.sessions.set(
      list.map((s) => ({
        id: s.name,
        name: s.name,
        title: s.title || s.name,
        updatedAt: s.ts || s.updated_at || Date.now(),
        messageCount: s.msgs || s.msg_count || 0,
        isCurrent: s.name === exports.activeSession.call(void 0, ),
      }))
    );
  } catch (err) {
    console.warn("loadSessions error:", err);
  }
} exports.loadSessions = loadSessions;

 async function loadFiles(query = "") {
  try {
    const res = await _net.apiFetch.call(void 0, `/api/files${getQuery({ q: query })}`);
    const items = Array.isArray(_optionalChain([res, 'optionalAccess', _7 => _7.items])) ? res.items : Array.isArray(res) ? res : [];
    exports.files.set(items);
  } catch (err) {
    console.warn("loadFiles error:", err);
  }
} exports.loadFiles = loadFiles;

 async function loadHistory() {
  try {
    const res = await _net.apiFetch.call(void 0, `/api/history${getQuery()}`);
    const rawList = Array.isArray(_optionalChain([res, 'optionalAccess', _8 => _8.history]))
      ? res.history
      : Array.isArray(_optionalChain([res, 'optionalAccess', _9 => _9.messages]))
      ? res.messages
      : Array.isArray(res)
      ? res
      : [];

    const turnList = [];
    let currentAssistantTurn = null;

    for (const m of rawList) {
      if (m.role === "user") {
        currentAssistantTurn = null;
        turnList.push({
          id: `u_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
          role: "user",
          content: m.content || "",
          steps: [],
          timestamp: m.timestamp || Date.now(),
        });
      } else if (m.role === "assistant") {
        currentAssistantTurn = {
          id: `a_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
          role: "assistant",
          content: m.content || "",
          thought: m.thought || m.reasoning || "",
          thoughtDurationMs: m.thought_duration,
          steps: [],
          timestamp: m.timestamp || Date.now(),
        };
        turnList.push(currentAssistantTurn);
      } else if (m.role === "tool") {
        const step = {
          id: `st_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
          name: m.name || "Tool",
          desc: typeof m.args === "string" ? m.args : JSON.stringify(m.args),
          status: "done",
          startedAt: Date.now(),
          result: m.content || "",
          args: m.args,
        };
        if (currentAssistantTurn) {
          currentAssistantTurn.steps.push(step);
        } else {
          currentAssistantTurn = {
            id: `a_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`,
            role: "assistant",
            content: "",
            steps: [step],
            timestamp: Date.now(),
          };
          turnList.push(currentAssistantTurn);
        }
      }
    }
    exports.turns.set(turnList);
  } catch (err) {
    console.warn("loadHistory error:", err);
  }
} exports.loadHistory = loadHistory;

 async function switchSession(name) {
  if (exports.activeSession.call(void 0, ) === name) return;
  exports.activeSession.set(name);
  await loadState();
  await loadHistory();
  await loadSessions();
} exports.switchSession = switchSession;

 async function createSession() {
  try {
    const res = await _net.apiFetch.call(void 0, `/api/action${getQuery()}`, {
      method: "POST",
      body: JSON.stringify({ act: "new" }),
    });
    if (res && res.name) {
      await switchSession(res.name);
    }
  } catch (err) {
    console.warn("createSession error:", err);
  }
} exports.createSession = createSession;

 async function renameSession(id, title) {
  try {
    const q = getQuery({ session: id });
    await _net.apiFetch.call(void 0, `/api/title${q}`, {
      method: "POST",
      body: JSON.stringify({ title }),
    });
    await loadSessions();
  } catch (err) {
    console.warn("renameSession error:", err);
  }
} exports.renameSession = renameSession;

 async function deleteSession(id) {
  try {
    const q = getQuery({ session: id });
    await _net.apiFetch.call(void 0, `/api/action${q}`, {
      method: "POST",
      body: JSON.stringify({ act: "delete" }),
    });
    if (exports.activeSession.call(void 0, ) === id) {
      exports.activeSession.set("default");
      await loadState();
      await loadHistory();
    }
    await loadSessions();
  } catch (err) {
    console.warn("deleteSession error:", err);
  }
} exports.deleteSession = deleteSession;

 async function switchMode(nextMode) {
  exports.mode.set(nextMode);
  setStored("mode", nextMode);
  try {
    await _net.apiFetch.call(void 0, `/api/mode${getQuery()}`, {
      method: "POST",
      body: JSON.stringify({ mode: nextMode }),
    });
  } catch (err) {
    console.warn("switchMode error:", err);
  }
} exports.switchMode = switchMode;

 async function switchModel(nextModel) {
  exports.model.set(nextModel);
  try {
    await _net.apiFetch.call(void 0, `/api/model${getQuery()}`, {
      method: "POST",
      body: JSON.stringify({ model: nextModel }),
    });
  } catch (err) {
    console.warn("switchModel error:", err);
  }
} exports.switchModel = switchModel;

 async function interrupt() {
  try {
    await _net.apiFetch.call(void 0, `/api/interrupt${getQuery()}`, { method: "POST" });
  } catch (err) {
    console.warn("interrupt error:", err);
  } finally {
    exports.isStreaming.set(false);
  }
} exports.interrupt = interrupt;

 async function approve(id, allow) {
  try {
    await _net.apiFetch.call(void 0, "/api/approve", {
      method: "POST",
      body: JSON.stringify({ id, allow }),
    });
    exports.pendingApproval.set(null);
  } catch (err) {
    console.warn("approve error:", err);
  }
} exports.approve = approve;

 async function sendMessage(text) {
  if (!text || !text.trim() || exports.isStreaming.call(void 0, )) return;

  const userTurn = {
    id: `u_${Date.now()}`,
    role: "user",
    content: text.trim(),
    steps: [],
    timestamp: Date.now(),
  };

  const assistantTurnId = `a_${Date.now()}`;
  const assistantTurn = {
    id: assistantTurnId,
    role: "assistant",
    content: "",
    thought: "",
    steps: [],
    timestamp: Date.now(),
    isStreaming: true,
  };

  _signal.batch.call(void 0, () => {
    exports.turns.update((prev) => [...prev, userTurn, assistantTurn]);
    exports.isStreaming.set(true);
    exports.streamingTurnId.set(assistantTurnId);
  });

  try {
    await _net.apiFetch.call(void 0, `/api/chat${getQuery()}`, {
      method: "POST",
      body: JSON.stringify({ message: text.trim() }),
    });
  } catch (err) {
    console.error("sendMessage failed:", err);
    _signal.batch.call(void 0, () => {
      exports.turns.update((prev) =>
        prev.map((t) =>
          t.id === assistantTurnId
            ? { ...t, content: `Error: ${err instanceof Error ? err.message : String(err)}`, isStreaming: false }
            : t
        )
      );
      exports.isStreaming.set(false);
      exports.streamingTurnId.set(null);
    });
  }
} exports.sendMessage = sendMessage;

// 核心 SSE 事件调度
 function handleSseEvent(event) {
  const { type, data } = event;

  switch (type) {
    case "stream_start":
      exports.isStreaming.set(true);
      break;

    case "stream": {
      const chunk = typeof data === "string" ? data : _optionalChain([data, 'optionalAccess', _10 => _10.chunk]) || "";
      const curId = exports.streamingTurnId.call(void 0, );
      if (curId) {
        exports.turns.update((prev) =>
          prev.map((t) =>
            t.id === curId ? { ...t, content: (t.content || "") + chunk } : t
          )
        );
      }
      break;
    }

    case "thought": {
      const thoughtChunk = typeof data === "string" ? data : _optionalChain([data, 'optionalAccess', _11 => _11.chunk]) || "";
      const curId = exports.streamingTurnId.call(void 0, );
      if (curId) {
        exports.turns.update((prev) =>
          prev.map((t) =>
            t.id === curId ? { ...t, thought: (t.thought || "") + thoughtChunk } : t
          )
        );
      }
      break;
    }

    case "step_start": {
      const curId = exports.streamingTurnId.call(void 0, );
      const step = {
        id: data.id || `st_${Date.now()}`,
        name: data.name || "Task Step",
        desc: data.desc,
        status: "running",
        startedAt: Date.now(),
        args: data.args,
      };
      if (curId) {
        exports.turns.update((prev) =>
          prev.map((t) =>
            t.id === curId ? { ...t, steps: [...t.steps, step] } : t
          )
        );
      }
      appendTerminalLine(`▶ [Step] ${step.name}: ${step.desc || ""}`, "cmd");
      break;
    }

    case "step_end": {
      const curId = exports.streamingTurnId.call(void 0, );
      if (curId && data.id) {
        exports.turns.update((prev) =>
          prev.map((t) =>
            t.id === curId
              ? {
                  ...t,
                  steps: t.steps.map((st) =>
                    st.id === data.id
                      ? {
                          ...st,
                          status: data.error ? "error" : "done",
                          durationMs: Date.now() - st.startedAt,
                          result: data.result,
                          error: data.error,
                        }
                      : st
                  ),
                }
              : t
          )
        );
      }
      break;
    }

    case "tool_diff": {
      if (data && data.diff) {
        const parsed = _diff.parseUnifiedDiff.call(void 0, data.diff);
        exports.diffs.set(parsed);
        if (parsed.length > 0) {
          exports.activeDiffPath.set(parsed[0].path);
          setDeckTab("diffs");
        }
      }
      break;
    }

    case "terminal_out": {
      const text = typeof data === "string" ? data : _optionalChain([data, 'optionalAccess', _12 => _12.text]) || "";
      appendTerminalLine(text, _optionalChain([data, 'optionalAccess', _13 => _13.stream]) === "stderr" ? "stderr" : "stdout");
      break;
    }

    case "job_update": {
      if (data && data.id) {
        exports.jobs.update((prev) => {
          const idx = prev.findIndex((j) => j.id === data.id);
          const item = {
            id: data.id,
            name: data.name || "Background Job",
            role: data.role,
            status: data.status || "running",
            startedAt: data.startedAt || Date.now(),
            finishedAt: data.finishedAt,
            summary: data.summary,
          };
          if (idx >= 0) {
            const next = [...prev];
            next[idx] = { ...next[idx], ...item };
            return next;
          }
          return [...prev, item];
        });
      }
      break;
    }

    case "permission_request": {
      if (data && data.id) {
        exports.pendingApproval.set({
          id: data.id,
          type: data.type || "execute",
          command: data.command,
          desc: data.desc,
          path: data.path,
        });
      }
      break;
    }

    case "stream_end":
      _signal.batch.call(void 0, () => {
        exports.isStreaming.set(false);
        const curId = exports.streamingTurnId.call(void 0, );
        if (curId) {
          exports.turns.update((prev) =>
            prev.map((t) => (t.id === curId ? { ...t, isStreaming: false } : t))
          );
        }
        exports.streamingTurnId.set(null);
      });
      loadState();
      break;
  }
} exports.handleSseEvent = handleSseEvent;

// 统一应用启动
 function boot() {
  document.documentElement.setAttribute("data-color-scheme", exports.theme.call(void 0, ));

  _net.connectEventStream.call(void 0, handleSseEvent, (st) => {
    exports.connectionStatus.set(st);
  });

  loadState();
  loadModels();
  loadSessions();
  loadHistory();
  loadFiles();

  window.addEventListener("piz:unauthorized", () => {
    exports.showAuthModal.set(true);
  });
} exports.boot = boot;

};
__modules["topbar"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// topbar.ts —— 顶栏工作台导航与全局状态指示
var _dom = require('./dom');





















var _store = require('./store');


 function renderTopBar() {
  return _dom.tags.header(
    { class: "topbar" },
    // 左侧：品牌与会话谱系
    _dom.tags.div(
      { class: "tb-left" },
      _dom.tags.button(
        {
          class: "tb-btn tb-icon-btn",
          title: "Toggle Sidebar (Ctrl+B)",
          onclick: _store.toggleSidebar,
        },
        _dom.tags.svg(
          { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2" },
          _dom.tags.path({ d: "M3 3h18v18H3z" }),
          _dom.tags.path({ d: "M9 3v18" })
        )
      ),
      _dom.tags.div(
        { class: "tb-brand" },
        _dom.tags.svg(
          { class: "tb-logo", viewBox: "0 0 24 18", fill: "currentColor" },
          _dom.tags.path({
            d: "M2.4 1.8h17.2a1.7 1.7 0 0 1 0 3.4H10l10 8.2A1.8 1.8 0 0 1 18.65 16.45H3.2a1.7 1.7 0 0 1 0-3.4h9.4L2.7 4.9A1.8 1.8 0 0 1 4.1 1.8z",
          })
        ),
        _dom.tags.span({ class: "tb-title" }, "piz")
      ),
      _dom.tags.span({ class: "tb-sep" }, "/"),
      // 工作区与分支
      () => {
        const w = _store.wsName.call(void 0, ) || "workspace";
        const b = _store.branch.call(void 0, );
        const ch = _store.changesCount.call(void 0, );
        const branchPart = b ? ` (${b})` : "";
        const chPart = ch > 0 ? ` · ${ch}Δ` : "";
        return _dom.tags.span({ class: "tb-ws-badge", title: `Workspace: ${w}${branchPart}` }, `${w}${branchPart}${chPart}`);
      },
      _dom.tags.span({ class: "tb-sep" }, "/"),
      _dom.tags.button(
        {
          class: "tb-session-btn",
          title: "Double click to rename session",
          ondblclick: () => {
            const cur = _store.activeSession.call(void 0, );
            const next = prompt("Rename session:", cur);
            if (next && next.trim()) _store.renameSession.call(void 0, cur, next.trim());
          },
        },
        () => {
          const cur = _store.activeSession.call(void 0, );
          const s = _store.sessions.call(void 0, ).find((x) => x.id === cur);
          return s ? s.title : cur;
        }
      )
    ),

    // 中间：模式切换胶囊
    _dom.tags.div(
      { class: "tb-center" },
      _dom.tags.div(
        { class: "mode-pill" },
        renderModeBtn("yolo", "⚡ YOLO", "Full auto-execution"),
        renderModeBtn("ask", "🛡 Ask", "Ask before destructive operations"),
        renderModeBtn("plan", "📋 Plan", "Analysis & plan only, no write")
      )
    ),

    // 右侧：模型、Token、Deck 开关、主题
    _dom.tags.div(
      { class: "tb-right" },
      // 搜索/命令面板
      _dom.tags.button(
        {
          class: "tb-btn tb-search-btn",
          title: "Search / Command Palette (Ctrl+K)",
          onclick: () => _store.showSearchModal.set(true),
        },
        _dom.tags.span({ class: "search-icon" }, "⌕"),
        _dom.tags.span({ class: "search-key" }, "⌘K")
      ),
      // 模型下拉
      _dom.tags.div(
        { class: "model-selector-wrap" },
        _dom.tags.select(
          {
            class: "model-select",
            value: () => _store.model.call(void 0, ),
            onchange: (e) => {
              const target = e.target ;
              if (target.value) _store.switchModel.call(void 0, target.value);
            },
          },
          () => {
            const list = _store.models.call(void 0, );
            const cur = _store.model.call(void 0, );
            const opts = list.map((m) =>
              _dom.tags.option({ value: m, selected: m === cur }, m)
            );
            if (cur && !list.includes(cur)) {
              opts.unshift(_dom.tags.option({ value: cur, selected: true }, cur));
            }
            return opts;
          }
        )
      ),
      // Token 使用率胶囊
      _dom.tags.div(
        {
          class: "token-pill",
          title: "Context Window Usage",
        },
        _dom.tags.span({ class: "token-dot" }),
        () => `${_store.pct.call(void 0, )}% ctx`
      ),
      // 工作台 Deck 切换按钮
      _dom.tags.button(
        {
          class: () => `tb-btn tb-deck-btn ${_store.deckOpen.call(void 0, ) ? "is-active" : ""}`,
          title: "Toggle Workspace Deck (Diffs/Terminal/Jobs)",
          onclick: _store.toggleDeck,
        },
        _dom.tags.svg(
          { viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2" },
          _dom.tags.path({ d: "M3 3h18v18H3z" }),
          _dom.tags.path({ d: "M15 3v18" })
        ),
        _dom.tags.span({ class: "tb-deck-label" }, "Deck")
      ),
      // 主题切换
      _dom.tags.button(
        {
          class: "tb-btn tb-icon-btn",
          title: "Toggle Theme",
          onclick: _store.toggleTheme,
        },
        () => (_store.theme.call(void 0, ) === "dark" ? "☀" : "🌙")
      ),
      // 设置按钮
      _dom.tags.button(
        {
          class: "tb-btn tb-icon-btn",
          title: "Settings",
          onclick: () => _store.showSettingsModal.set(true),
        },
        "⚙"
      ),
      // 网络状态指示灯
      _dom.tags.span({
        class: () => `status-indicator ${_store.connectionStatus.call(void 0, )}`,
        title: () => `Connection: ${_store.connectionStatus.call(void 0, )}`,
      })
    )
  );
} exports.renderTopBar = renderTopBar;

function renderModeBtn(m, label, title) {
  return _dom.tags.button(
    {
      class: () => `mode-btn ${_store.mode.call(void 0, ) === m ? "is-active" : ""}`,
      title,
      onclick: () => _store.switchMode.call(void 0, m),
    },
    label
  );
}

};
__modules["sidebar"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// sidebar.ts —— 侧边会话抽屉与多会话管理
var _dom = require('./dom');








var _store = require('./store');
var _signal = require('./signal');


 function renderSidebar() {
  const searchQuery = _signal.signal("");

  const filteredSessions = () => {
    const q = searchQuery().toLowerCase().trim();
    const list = _store.sessions.call(void 0, );
    if (!q) return list;
    return list.filter((s) => (s.title || s.name).toLowerCase().includes(q));
  };

  return _dom.tags.aside(
    {
      class: () => `sidebar ${_store.sidebarOpen.call(void 0, ) ? "is-open" : "is-collapsed"}`,
    },
    // 侧栏顶操作
    _dom.tags.div(
      { class: "sidebar-hdr" },
      _dom.tags.button(
        {
          class: "new-session-btn",
          onclick: _store.createSession,
        },
        _dom.tags.span({ class: "btn-icon" }, "＋"),
        _dom.tags.span({ class: "btn-text" }, "New Session")
      )
    ),

    // 搜索框
    _dom.tags.div(
      { class: "sidebar-search-box" },
      _dom.tags.input({
        class: "sidebar-search-input",
        placeholder: "Filter sessions...",
        value: () => searchQuery(),
        oninput: (e) => {
          searchQuery.set((e.target ).value);
        },
      })
    ),

    // 会话列表
    _dom.tags.div(
      { class: "sidebar-list" },
      _dom.each.call(void 0, filteredSessions, (item) => {
        const isCurrent = () => _store.activeSession.call(void 0, ) === item.id;

        return _dom.tags.div(
          {
            class: () => `session-item ${isCurrent() ? "is-active" : ""}`,
            onclick: () => _store.switchSession.call(void 0, item.id),
          },
          _dom.tags.div(
            { class: "session-item-body" },
            _dom.tags.div({ class: "session-title" }, item.title || item.name),
            _dom.tags.div(
              { class: "session-meta" },
              _dom.tags.span({ class: "session-badge" }, `${item.messageCount} msgs`),
              _dom.tags.span({ class: "session-time" }, formatRelativeTime(item.updatedAt))
            )
          ),
          // 悬浮操作
          _dom.tags.div(
            { class: "session-actions", onclick: (e) => e.stopPropagation() },
            _dom.tags.button(
              {
                class: "session-act-btn",
                title: "Rename",
                onclick: () => {
                  const val = prompt("Rename session:", item.title || item.name);
                  if (val && val.trim()) _store.renameSession.call(void 0, item.id, val.trim());
                },
              },
              "✎"
            ),
            _dom.tags.button(
              {
                class: "session-act-btn session-del-btn",
                title: "Delete",
                onclick: () => {
                  if (confirm(`Delete session "${item.title || item.name}"?`)) {
                    _store.deleteSession.call(void 0, item.id);
                  }
                },
              },
              "🗑"
            )
          )
        );
      })
    ),

    // 侧栏底端状态
    _dom.tags.div(
      { class: "sidebar-footer" },
      _dom.tags.span({ class: "sidebar-info" }, () => `${_store.sessions.call(void 0, ).length} sessions`)
    )
  );
} exports.renderSidebar = renderSidebar;

function formatRelativeTime(ts) {
  if (!ts) return "";
  const sec = Math.max(1, Math.floor((Date.now() - ts) / 1000));
  if (sec < 60) return `${sec}s ago`;
  const min = Math.floor(sec / 60);
  if (min < 60) return `${min}m ago`;
  const hr = Math.floor(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const days = Math.floor(hr / 24);
  return `${days}d ago`;
}

};
__modules["md"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// md.ts —— 极速安全 Markdown 渲染器 (Fail-closed 防 XSS，流式容错)

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderInline(text) {
  let s = escapeHtml(text);

  // 行内代码 `code`
  s = s.replace(/`([^`]+)`/g, '<code class="inline-code">$1</code>');
  // 粗体 **bold** or __bold__
  s = s.replace(/(\*\*|__)(.*?)\1/g, "<strong>$2</strong>");
  // 斜体 *italic* or _italic_
  s = s.replace(/(\*|_)(.*?)\1/g, "<em>$2</em>");
  // 删除线 ~~del~~
  s = s.replace(/~~(.*?)~~/g, "<del>$1</del>");
  // 链接 [text](url)
  s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer" class="md-link">$1</a>');

  return s;
}

 function renderMarkdown(markdown) {
  if (!markdown) return "";

  const lines = markdown.split(/\r?\n/);
  const out = [];
  let inCodeBlock = false;
  let codeBlockLang = "";
  let codeBlockContent = [];
  let inTable = false;
  let inList = false;
  let inBlockquote = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // 代码块判定 ```lang
    if (line.trim().startsWith("```")) {
      if (inCodeBlock) {
        // 闭合代码块
        const codeText = escapeHtml(codeBlockContent.join("\n"));
        out.push(
          `<div class="code-block" data-lang="${codeBlockLang}">` +
            `<div class="code-block-hdr">` +
              `<span class="code-lang">${codeBlockLang || "text"}</span>` +
              `<button class="copy-btn" onclick="navigator.clipboard.writeText(this.closest('.code-block').querySelector('code').innerText);this.textContent='Copied!';setTimeout(()=>this.textContent='Copy',1500)">Copy</button>` +
            `</div>` +
            `<pre><code class="lang-${codeBlockLang}">${codeText}</code></pre>` +
          `</div>`
        );
        inCodeBlock = false;
        codeBlockLang = "";
        codeBlockContent = [];
      } else {
        // 打开代码块
        inCodeBlock = true;
        codeBlockLang = line.trim().slice(3).trim();
        codeBlockContent = [];
      }
      continue;
    }

    if (inCodeBlock) {
      codeBlockContent.push(line);
      continue;
    }

    // 表格判定 | a | b |
    if (line.trim().startsWith("|") && line.trim().endsWith("|")) {
      if (!inTable) {
        inTable = true;
        out.push('<div class="table-wrap"><table>');
      }
      // 忽略分隔线 |---|---|
      if (/^\|[\s\-:|]+\|$/.test(line.trim())) {
        continue;
      }
      const cells = line
        .trim()
        .slice(1, -1)
        .split("|")
        .map((c) => c.trim());
      const isHeader = i + 1 < lines.length && /^\|[\s\-:|]+\|$/.test(lines[i + 1].trim());
      const tag = isHeader ? "th" : "td";
      out.push("<tr>" + cells.map((c) => `<${tag}>${renderInline(c)}</${tag}>`).join("") + "</tr>");
      continue;
    } else if (inTable) {
      inTable = false;
      out.push("</table></div>");
    }

    // 引用块 > quote
    if (line.startsWith("> ") || line === ">") {
      if (!inBlockquote) {
        inBlockquote = true;
        out.push("<blockquote>");
      }
      out.push(`<p>${renderInline(line.slice(2))}</p>`);
      continue;
    } else if (inBlockquote) {
      inBlockquote = false;
      out.push("</blockquote>");
    }

    // 列表判定 - item or * item or 1. item
    const listMatch = line.match(/^(\s*)([-*]|\d+\.)\s+(.*)$/);
    if (listMatch) {
      if (!inList) {
        inList = true;
        out.push("<ul>");
      }
      let content = listMatch[3];
      // 任务列表 [ ] or [x]
      if (content.startsWith("[ ] ")) {
        content = `<input type="checkbox" disabled class="task-chk"> ` + content.slice(4);
      } else if (content.startsWith("[x] ")) {
        content = `<input type="checkbox" checked disabled class="task-chk"> ` + content.slice(4);
      }
      out.push(`<li>${renderInline(content)}</li>`);
      continue;
    } else if (inList) {
      inList = false;
      out.push("</ul>");
    }

    // 空行
    if (!line.trim()) {
      continue;
    }

    // 标题 # ## ###
    const hMatch = line.match(/^(#{1,6})\s+(.*)$/);
    if (hMatch) {
      const level = hMatch[1].length;
      out.push(`<h${level}>${renderInline(hMatch[2])}</h${level}>`);
      continue;
    }

    // 分隔线 ---
    if (/^(\*{3,}|-{3,}|_{3,})$/.test(line.trim())) {
      out.push("<hr />");
      continue;
    }

    // 常规段落
    out.push(`<p>${renderInline(line)}</p>`);
  }

  // 兜底闭合流式未完结结构
  if (inCodeBlock) {
    const codeText = escapeHtml(codeBlockContent.join("\n"));
    out.push(
      `<div class="code-block is-streaming" data-lang="${codeBlockLang}">` +
        `<div class="code-block-hdr">` +
          `<span class="code-lang">${codeBlockLang || "text"}</span>` +
        `</div>` +
        `<pre><code class="lang-${codeBlockLang}">${codeText}</code></pre>` +
      `</div>`
    );
  }
  if (inTable) out.push("</table></div>");
  if (inBlockquote) out.push("</blockquote>");
  if (inList) out.push("</ul>");

  return out.join("\n");
} exports.renderMarkdown = renderMarkdown;

};
__modules["chat"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// chat.ts —— 对话流视图 (Turn 境界、思考流折叠、步骤轨迹与 Markdown 渲染)
var _dom = require('./dom');
var _store = require('./store');
var _md = require('./md');

var _signal = require('./signal');

 function renderChatStream() {
  let userScrolledUp = false;

  const container = _dom.tags.div(
    {
      class: "chat-stream",
      onscroll: (e) => {
        const el = e.target ;
        const distFromBottom = el.scrollHeight - el.scrollTop - el.clientHeight;
        userScrolledUp = distFromBottom > 80;
      },
    },
    // 渲染每一轮对话
    _dom.each.call(void 0, _store.turns, (turn) => {
      if (turn.role === "user") {
        return renderUserTurn(turn);
      } else {
        return renderAssistantTurn(turn);
      }
    }),
    // 空态欢迎页
    () => {
      if (_store.turns.call(void 0, ).length === 0) {
        return renderEmptyState();
      }
      return null;
    }
  );

  // 自动滚动到底部
  _signal.effect.call(void 0, () => {
    // 触发依赖
    _store.turns.call(void 0, );
    _store.isStreaming.call(void 0, );
    if (!userScrolledUp) {
      setTimeout(() => {
        container.scrollTop = container.scrollHeight;
      }, 20);
    }
  });

  return container;
} exports.renderChatStream = renderChatStream;

function renderEmptyState() {
  return _dom.tags.div(
    { class: "chat-empty-state" },
    _dom.tags.div(
      { class: "empty-brand" },
      _dom.tags.svg(
        { class: "empty-logo", viewBox: "0 0 24 18", fill: "currentColor" },
        _dom.tags.path({
          d: "M2.4 1.8h17.2a1.7 1.7 0 0 1 0 3.4H10l10 8.2A1.8 1.8 0 0 1 18.65 16.45H3.2a1.7 1.7 0 0 1 0-3.4h9.4L2.7 4.9A1.8 1.8 0 0 1 4.1 1.8z",
        })
      ),
      _dom.tags.h2({ class: "empty-title" }, "piz - Agentic Workspace"),
      _dom.tags.p({ class: "empty-subtitle" }, "极速、安全的下一代自律型智能体工作台")
    ),
    _dom.tags.div(
      { class: "empty-prompts" },
      _dom.tags.div(
        { class: "prompt-card" },
        _dom.tags.div({ class: "prompt-card-title" }, "⚡ 快速诊断与修复"),
        _dom.tags.div({ class: "prompt-card-desc" }, "分析编译报错、内存泄漏或逻辑缺陷并立即提出补丁")
      ),
      _dom.tags.div(
        { class: "prompt-card" },
        _dom.tags.div({ class: "prompt-card-title" }, "🛠 代码审查与 Diff"),
        _dom.tags.div({ class: "prompt-card-desc" }, "在右侧检视台实时审查变更行数、Hunk 差异与终端输出")
      ),
      _dom.tags.div(
        { class: "prompt-card" },
        _dom.tags.div({ class: "prompt-card-title" }, "🛡 安全审计与攻防"),
        _dom.tags.div({ class: "prompt-card-desc" }, "污点分析、权限防范、最小权限原则审查与闭环验证")
      )
    )
  );
}

function renderUserTurn(turn) {
  return _dom.tags.div(
    { class: "turn turn-user", id: turn.id },
    _dom.tags.div(
      { class: "turn-inner" },
      _dom.tags.div({ class: "turn-avatar user-avatar" }, "U"),
      _dom.tags.div(
        { class: "turn-body" },
        _dom.tags.div({ class: "user-bubble" }, turn.content)
      )
    )
  );
}

function renderAssistantTurn(turn) {
  const thoughtCollapsed = _signal.signal(!turn.isStreaming && Boolean(turn.content));

  return _dom.tags.div(
    { class: "turn turn-assistant", id: turn.id },
    _dom.tags.div(
      { class: "turn-inner" },
      _dom.tags.div({ class: "turn-avatar assistant-avatar" }, "π"),
      _dom.tags.div(
        { class: "turn-body" },
        // 1. 思考流折叠
        () => {
          if (!turn.thought && !turn.isStreaming) return null;
          if (!turn.thought && turn.isStreaming && turn.steps.length === 0) {
            return _dom.tags.div(
              { class: "thought-panel is-thinking" },
              _dom.tags.span({ class: "thought-spinner" }),
              _dom.tags.span({ class: "thought-label" }, "Thinking...")
            );
          }
          if (!turn.thought) return null;

          const durationText = turn.thoughtDurationMs
            ? ` (${(turn.thoughtDurationMs / 1000).toFixed(1)}s)`
            : "";

          return _dom.tags.div(
            { class: "thought-panel" },
            _dom.tags.div(
              {
                class: "thought-header",
                onclick: () => thoughtCollapsed.set(!thoughtCollapsed()),
              },
              _dom.tags.span({ class: "thought-chevron" }, () =>
                thoughtCollapsed() ? "▸" : "▾"
              ),
              _dom.tags.span({ class: "thought-title" }, `Thinking Process${durationText}`),
              turn.isStreaming
                ? _dom.tags.span({ class: "thought-live-badge" }, "LIVE")
                : null
            ),
            () => {
              if (thoughtCollapsed()) return null;
              return _dom.tags.div({ class: "thought-content" }, turn.thought || "");
            }
          );
        },

        // 2. 步骤执行轨 (Step Track)
        () => {
          if (!turn.steps || turn.steps.length === 0) return null;
          return _dom.tags.div(
            { class: "step-track" },
            turn.steps.map((st) => renderStepCard(st))
          );
        },

        // 3. 正文 Markdown
        () => {
          const content = turn.content || "";
          if (!content && turn.isStreaming) {
            return _dom.tags.div({ class: "markdown-body is-generating" }, _dom.tags.span({ class: "typing-cursor" }));
          }

          const html = _md.renderMarkdown.call(void 0, content);
          const el = _dom.tags.div({ class: "markdown-body" });
          el.innerHTML = html;
          if (turn.isStreaming) {
            const cursor = document.createElement("span");
            cursor.className = "typing-cursor";
            el.appendChild(cursor);
          }
          return el;
        }
      )
    )
  );
}

function renderStepCard(step) {
  const isExpanded = _signal.signal(false);

  return _dom.tags.div(
    {
      class: () => `step-card status-${step.status}`,
    },
    _dom.tags.div(
      {
        class: "step-card-hdr",
        onclick: () => isExpanded.set(!isExpanded()),
      },
      _dom.tags.span({ class: "step-status-icon" }, () => {
        if (step.status === "running") return "⟳";
        if (step.status === "error") return "✕";
        return "✓";
      }),
      _dom.tags.span({ class: "step-name" }, step.name),
      step.desc ? _dom.tags.span({ class: "step-desc" }, step.desc) : null,
      _dom.tags.span(
        { class: "step-time" },
        step.durationMs ? `${(step.durationMs / 1000).toFixed(2)}s` : "..."
      ),
      _dom.tags.span({ class: "step-chevron" }, () => (isExpanded() ? "▴" : "▾"))
    ),
    // 展开查看详情
    () => {
      if (!isExpanded()) return null;
      return _dom.tags.div(
        { class: "step-details" },
        step.args
          ? _dom.tags.div(
              { class: "step-detail-row" },
              _dom.tags.div({ class: "step-detail-lbl" }, "Arguments:"),
              _dom.tags.pre(
                { class: "step-detail-pre" },
                typeof step.args === "string"
                  ? step.args
                  : JSON.stringify(step.args, null, 2)
              )
            )
          : null,
        step.result
          ? _dom.tags.div(
              { class: "step-detail-row" },
              _dom.tags.div({ class: "step-detail-lbl" }, "Result:"),
              _dom.tags.pre({ class: "step-detail-pre" }, step.result)
            )
          : null,
        step.error
          ? _dom.tags.div(
              { class: "step-detail-row step-error" },
              _dom.tags.div({ class: "step-detail-lbl" }, "Error:"),
              _dom.tags.pre({ class: "step-detail-pre" }, step.error)
            )
          : null,
        _dom.tags.div(
          { class: "step-actions" },
          _dom.tags.button(
            {
              class: "step-deck-btn",
              onclick: () => {
                _store.appendTerminalLine.call(void 0, `=== Step ${step.name} ===\n${step.result || step.error || ""}`, "system");
                _store.setDeckTab.call(void 0, "terminal");
              },
            },
            "Send to Terminal"
          )
        )
      );
    }
  );
}

};
__modules["composer"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// composer.ts —— 底部智能输入台 (自适应高度、斜杠补全、文件引用与流控)
var _dom = require('./dom');









var _store = require('./store');
var _signal = require('./signal');

 function renderComposer() {
  const text = _signal.signal("");
  const showSlashMenu = _signal.signal(false);
  const showFileMenu = _signal.signal(false);
  const menuIndex = _signal.signal(0);

  let textareaEl = null;

  const SLASH_COMMANDS = [
    { cmd: "/help", desc: "Show available commands and usage" },
    { cmd: "/diff", desc: "Open right deck to view code changes" },
    { cmd: "/term", desc: "Open terminal viewer in deck" },
    { cmd: "/jobs", desc: "View subagent hierarchy and jobs" },
    { cmd: "/files", desc: "Browse workspace files" },
    { cmd: "/clear", desc: "Create a fresh new session" },
    { cmd: "/yolo", desc: "Switch mode to YOLO (auto-execute)" },
    { cmd: "/ask", desc: "Switch mode to Ask (require approval)" },
  ];

  function handleInput(e) {
    const el = e.target ;
    text.set(el.value);
    autoResize(el);

    const val = el.value;
    if (val.startsWith("/")) {
      showSlashMenu.set(true);
      showFileMenu.set(false);
      menuIndex.set(0);
    } else if (val.includes("@")) {
      showFileMenu.set(true);
      showSlashMenu.set(false);
      menuIndex.set(0);
    } else {
      showSlashMenu.set(false);
      showFileMenu.set(false);
    }
  }

  function autoResize(el) {
    el.style.height = "auto";
    const nextH = Math.min(Math.max(el.scrollHeight, 40), 220);
    el.style.height = `${nextH}px`;
  }

  function doSend() {
    const msg = text().trim();
    if (!msg || _store.isStreaming.call(void 0, )) return;

    // 本地拦截部分斜杠命令
    if (msg === "/diff") {
      _store.setDeckTab.call(void 0, "diffs");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/term") {
      _store.setDeckTab.call(void 0, "terminal");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/jobs") {
      _store.setDeckTab.call(void 0, "jobs");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/files") {
      _store.setDeckTab.call(void 0, "files");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/clear") {
      _store.createSession.call(void 0, );
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/yolo") {
      _store.switchMode.call(void 0, "yolo");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }
    if (msg === "/ask") {
      _store.switchMode.call(void 0, "ask");
      text.set("");
      if (textareaEl) textareaEl.value = "";
      return;
    }

    _store.sendMessage.call(void 0, msg);
    text.set("");
    if (textareaEl) {
      textareaEl.value = "";
      autoResize(textareaEl);
    }
    showSlashMenu.set(false);
    showFileMenu.set(false);
  }

  function handleKeyDown(e) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      doSend();
    } else if (e.key === "Escape") {
      showSlashMenu.set(false);
      showFileMenu.set(false);
    }
  }

  return _dom.tags.div(
    { class: "composer-wrap" },
    // 斜杠菜单浮层
    () => {
      if (!showSlashMenu()) return null;
      const q = text().toLowerCase();
      const filtered = SLASH_COMMANDS.filter((c) => c.cmd.toLowerCase().startsWith(q));
      if (!filtered.length) return null;

      return _dom.tags.div(
        { class: "popup-menu slash-menu" },
        filtered.map((item, idx) =>
          _dom.tags.div(
            {
              class: () => `menu-item ${menuIndex() === idx ? "is-selected" : ""}`,
              onclick: () => {
                text.set(item.cmd + " ");
                if (textareaEl) {
                  textareaEl.value = item.cmd + " ";
                  textareaEl.focus();
                }
                showSlashMenu.set(false);
              },
            },
            _dom.tags.span({ class: "menu-cmd" }, item.cmd),
            _dom.tags.span({ class: "menu-desc" }, item.desc)
          )
        )
      );
    },

    // @文件菜单浮层
    () => {
      if (!showFileMenu()) return null;
      const atIdx = text().lastIndexOf("@");
      const q = atIdx >= 0 ? text().slice(atIdx + 1).toLowerCase() : "";
      const filtered = _store.files.call(void 0, )
        .filter((f) => !f.dir && f.path.toLowerCase().includes(q))
        .slice(0, 10);
      if (!filtered.length) return null;

      return _dom.tags.div(
        { class: "popup-menu file-menu" },
        filtered.map((f, idx) =>
          _dom.tags.div(
            {
              class: () => `menu-item ${menuIndex() === idx ? "is-selected" : ""}`,
              onclick: () => {
                const before = text().slice(0, atIdx);
                const nextVal = `${before}@${f.path} `;
                text.set(nextVal);
                if (textareaEl) {
                  textareaEl.value = nextVal;
                  textareaEl.focus();
                }
                showFileMenu.set(false);
              },
            },
            _dom.tags.span({ class: "file-icon" }, "📄"),
            _dom.tags.span({ class: "file-path" }, f.path)
          )
        )
      );
    },

    // 主输入框容器
    _dom.tags.div(
      { class: "composer-box" },
      _dom.tags.textarea({
        class: "composer-input",
        placeholder: "Ask piz or type '/' for commands, '@' to reference files...",
        rows: "1",
        value: () => text(),
        oninput: handleInput,
        onkeydown: handleKeyDown,
        ref: (el) => {
          textareaEl = el;
        },
      }),

      // 控制栏底排
      _dom.tags.div(
        { class: "composer-bar" },
        _dom.tags.div(
          { class: "composer-bar-left" },
          _dom.tags.button(
            {
              class: "bar-tag-btn",
              title: "Trigger Slash Commands",
              onclick: () => {
                text.set("/");
                if (textareaEl) {
                  textareaEl.value = "/";
                  textareaEl.focus();
                }
                showSlashMenu.set(true);
              },
            },
            "/"
          ),
          _dom.tags.button(
            {
              class: "bar-tag-btn",
              title: "Reference File",
              onclick: () => {
                text.update((v) => v + "@");
                if (textareaEl) {
                  textareaEl.value = text();
                  textareaEl.focus();
                }
                showFileMenu.set(true);
              },
            },
            "@"
          ),
          _dom.tags.span(
            { class: "mode-indicator-label" },
            () => `Mode: ${_store.mode.call(void 0, ).toUpperCase()}`
          )
        ),
        _dom.tags.div(
          { class: "composer-bar-right" },
          () => {
            if (_store.isStreaming.call(void 0, )) {
              return _dom.tags.button(
                {
                  class: "composer-send-btn is-stop",
                  title: "Interrupt Generation (Esc)",
                  onclick: _store.interrupt,
                },
                _dom.tags.span({ class: "btn-stop-icon" }, "■"),
                _dom.tags.span({}, "Stop")
              );
            }
            return _dom.tags.button(
              {
                class: "composer-send-btn",
                title: "Send message (Enter)",
                onclick: doSend,
              },
              _dom.tags.span({ class: "btn-send-icon" }, "↑"),
              _dom.tags.span({}, "Send")
            );
          }
        )
      )
    )
  );
} exports.renderComposer = renderComposer;

};
__modules["term"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// term.ts —— 高保真 ANSI 颜色与控制序列转译器

const ANSI_COLORS = {
  30: "ansi-black",
  31: "ansi-red",
  32: "ansi-green",
  33: "ansi-yellow",
  34: "ansi-blue",
  35: "ansi-magenta",
  36: "ansi-cyan",
  37: "ansi-white",
  90: "ansi-bright-black",
  91: "ansi-bright-red",
  92: "ansi-bright-green",
  93: "ansi-bright-yellow",
  94: "ansi-bright-blue",
  95: "ansi-bright-magenta",
  96: "ansi-bright-cyan",
  97: "ansi-bright-white",
};

const ANSI_BG_COLORS = {
  40: "ansi-bg-black",
  41: "ansi-bg-red",
  42: "ansi-bg-green",
  43: "ansi-bg-yellow",
  44: "ansi-bg-blue",
  45: "ansi-bg-magenta",
  46: "ansi-bg-cyan",
  47: "ansi-bg-white",
};

 function ansiToHtml(input) {
  if (!input) return "";

  // 1. 转义基础 HTML 实体
  let s = input
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // 2. 状态机解析 ANSI 转义码 \x1b[...m
  const re = /\x1b\[([0-9;]*)m/g;
  let out = "";
  let lastIdx = 0;
  const activeClasses = new Set();

  let match;
  while ((match = re.exec(s)) !== null) {
    const textChunk = s.slice(lastIdx, match.index);
    if (textChunk) {
      if (activeClasses.size > 0) {
        out += `<span class="${Array.from(activeClasses).join(" ")}">${textChunk}</span>`;
      } else {
        out += textChunk;
      }
    }
    lastIdx = re.lastIndex;

    const codes = match[1] ? match[1].split(";").map(Number) : [0];
    for (const code of codes) {
      if (code === 0) {
        activeClasses.clear();
      } else if (code === 1) {
        activeClasses.add("ansi-bold");
      } else if (code === 2) {
        activeClasses.add("ansi-dim");
      } else if (code === 3) {
        activeClasses.add("ansi-italic");
      } else if (code === 4) {
        activeClasses.add("ansi-underline");
      } else if (ANSI_COLORS[code]) {
        // 清理旧前景色
        for (const cls of activeClasses) {
          if (cls.startsWith("ansi-") && !cls.startsWith("ansi-bg-") && !cls.startsWith("ansi-bold") && !cls.startsWith("ansi-dim") && !cls.startsWith("ansi-italic") && !cls.startsWith("ansi-underline")) {
            activeClasses.delete(cls);
          }
        }
        activeClasses.add(ANSI_COLORS[code]);
      } else if (ANSI_BG_COLORS[code]) {
        for (const cls of activeClasses) {
          if (cls.startsWith("ansi-bg-")) activeClasses.delete(cls);
        }
        activeClasses.add(ANSI_BG_COLORS[code]);
      }
    }
  }

  const remaining = s.slice(lastIdx);
  if (remaining) {
    if (activeClasses.size > 0) {
      out += `<span class="${Array.from(activeClasses).join(" ")}">${remaining}</span>`;
    } else {
      out += remaining;
    }
  }

  return out;
} exports.ansiToHtml = ansiToHtml;

};
__modules["deck"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// deck.ts —— 右侧工作台检视 Deck (Diffs/Terminal/Jobs/Files)
var _dom = require('./dom');














var _store = require('./store');
var _term = require('./term');

var _signal = require('./signal');
var _net = require('./net');

 function renderDeck() {
  return _dom.tags.aside(
    {
      class: () => `workbench-deck ${_store.deckOpen.call(void 0, ) ? "is-open" : "is-closed"}`,
    },
    // Deck 顶栏选项卡
    _dom.tags.header(
      { class: "deck-header" },
      _dom.tags.div(
        { class: "deck-tabs" },
        renderDeckTabBtn("diffs", "Diffs", () => {
          const st = _store.totalDiffStats.call(void 0, );
          return st.files > 0 ? `${st.files}` : "";
        }),
        renderDeckTabBtn("terminal", "Terminal", () => {
          const len = _store.terminalLines.call(void 0, ).length;
          return len > 0 ? `${len}` : "";
        }),
        renderDeckTabBtn("jobs", "Jobs", () => {
          const runCount = _store.jobs.call(void 0, ).filter((j) => j.status === "running").length;
          return runCount > 0 ? `${runCount}` : "";
        }),
        renderDeckTabBtn("files", "Files")
      ),
      _dom.tags.div(
        { class: "deck-header-actions" },
        _dom.tags.button(
          {
            class: "deck-close-btn",
            title: "Close Deck (Ctrl+J)",
            onclick: _store.toggleDeck,
          },
          "✕"
        )
      )
    ),

    // Deck 主体内容区（根据 deckTab 响应式切换）
    _dom.tags.div(
      { class: "deck-body" },
      () => {
        const current = _store.deckTab.call(void 0, );
        switch (current) {
          case "diffs":
            return renderDiffsPanel();
          case "terminal":
            return renderTerminalPanel();
          case "jobs":
            return renderJobsPanel();
          case "files":
            return renderFilesPanel();
        }
      }
    )
  );
} exports.renderDeck = renderDeck;

function renderDeckTabBtn(tab, title, badgeFn) {
  return _dom.tags.button(
    {
      class: () => `deck-tab-btn ${_store.deckTab.call(void 0, ) === tab ? "is-active" : ""}`,
      onclick: () => _store.setDeckTab.call(void 0, tab),
    },
    _dom.tags.span({}, title),
    () => {
      const badge = badgeFn ? badgeFn() : "";
      if (!badge) return null;
      return _dom.tags.span({ class: "deck-tab-badge" }, badge);
    }
  );
}

// 1. Diffs 面板
function renderDiffsPanel() {
  const list = _store.diffs.call(void 0, );
  const active = _store.activeDiffFile.call(void 0, );
  const stats = _store.totalDiffStats.call(void 0, );

  if (list.length === 0) {
    return _dom.tags.div(
      { class: "deck-empty" },
      _dom.tags.div({ class: "deck-empty-icon" }, "⌥"),
      _dom.tags.div({ class: "deck-empty-title" }, "No Changeset Detected"),
      _dom.tags.div({ class: "deck-empty-desc" }, "File modifications generated by agent will stream here in real time.")
    );
  }

  return _dom.tags.div(
    { class: "diff-panel" },
    // 变更文件选择条
    _dom.tags.div(
      { class: "diff-toolbar" },
      _dom.tags.div(
        { class: "diff-stats" },
        _dom.tags.span({ class: "diff-stat-add" }, `+${stats.additions}`),
        _dom.tags.span({ class: "diff-stat-del" }, `-${stats.deletions}`),
        _dom.tags.span({ class: "diff-stat-files" }, `${stats.files} files`)
      ),
      _dom.tags.div(
        { class: "diff-file-tabs" },
        list.map((file) =>
          _dom.tags.button(
            {
              class: () =>
                `diff-file-btn ${active && active.path === file.path ? "is-active" : ""}`,
              onclick: () => _store.activeDiffPath.set(file.path),
            },
            _dom.tags.span({ class: `diff-status-pill status-${file.status}` }, file.status[0].toUpperCase()),
            _dom.tags.span({ class: "diff-tab-path" }, file.path),
            _dom.tags.span({ class: "diff-tab-delta" }, `+${file.additions} -${file.deletions}`)
          )
        )
      )
    ),

    // 当前选中的 Diff 视窗
    _dom.tags.div(
      { class: "diff-viewport" },
      active
        ? _dom.tags.div(
            { class: "diff-file-view" },
            _dom.tags.div(
              { class: "diff-hunk-list" },
              active.hunks.map((hunk) =>
                _dom.tags.div(
                  { class: "diff-hunk" },
                  _dom.tags.div({ class: "diff-hunk-header" }, hunk.header),
                  _dom.tags.div(
                    { class: "diff-lines" },
                    hunk.lines.map((line) =>
                      _dom.tags.div(
                        { class: `diff-line line-${line.type}` },
                        _dom.tags.span({ class: "diff-line-old" }, line.oldNo ? String(line.oldNo) : ""),
                        _dom.tags.span({ class: "diff-line-new" }, line.newNo ? String(line.newNo) : ""),
                        _dom.tags.span({ class: "diff-line-marker" }, line.type === "add" ? "+" : line.type === "del" ? "-" : " "),
                        _dom.tags.span({ class: "diff-line-content" }, line.content)
                      )
                    )
                  )
                )
              )
            )
          )
        : null
    )
  );
}

// 2. Terminal 面板
function renderTerminalPanel() {
  const autoScroll = _signal.signal(true);
  let termEl = null;

  _signal.effect.call(void 0, () => {
    _store.terminalLines.call(void 0, );
    if (autoScroll() && termEl) {
      setTimeout(() => {
        if (termEl) termEl.scrollTop = termEl.scrollHeight;
      }, 10);
    }
  });

  return _dom.tags.div(
    { class: "terminal-panel" },
    // 终端控制条
    _dom.tags.div(
      { class: "terminal-bar" },
      _dom.tags.div({ class: "terminal-bar-title" }, "Agent Output Terminal"),
      _dom.tags.div(
        { class: "terminal-bar-actions" },
        _dom.tags.button(
          {
            class: () => `term-act-btn ${autoScroll() ? "is-active" : ""}`,
            title: "Toggle Auto Scroll",
            onclick: () => autoScroll.set(!autoScroll()),
          },
          "Auto-scroll"
        ),
        _dom.tags.button(
          {
            class: "term-act-btn",
            title: "Clear output",
            onclick: () => _store.terminalLines.set([]),
          },
          "Clear"
        ),
        _dom.tags.button(
          {
            class: "term-act-btn",
            title: "Copy all output",
            onclick: () => {
              const full = _store.terminalLines.call(void 0, ).map((l) => l.text).join("\n");
              navigator.clipboard.writeText(full);
            },
          },
          "Copy"
        )
      )
    ),

    // 终端输出流
    _dom.tags.div(
      {
        class: "terminal-screen",
        ref: (el) => {
          termEl = el;
        },
      },
      _dom.each.call(void 0, _store.terminalLines, (line) => {
        const row = _dom.tags.div({ class: `term-row row-${line.type}` });
        row.innerHTML = `<span class="term-time">${line.time}</span> <span class="term-text">${_term.ansiToHtml.call(void 0, line.text)}</span>`;
        return row;
      }),
      () => {
        if (_store.terminalLines.call(void 0, ).length === 0) {
          return _dom.tags.div({ class: "term-empty" }, "Terminal idle. Commands and logs will stream here.");
        }
        return null;
      }
    )
  );
}

// 3. Jobs 面板
function renderJobsPanel() {
  const list = _store.jobs.call(void 0, );

  if (list.length === 0) {
    return _dom.tags.div(
      { class: "deck-empty" },
      _dom.tags.div({ class: "deck-empty-icon" }, "⚙"),
      _dom.tags.div({ class: "deck-empty-title" }, "No Active Subagent Jobs"),
      _dom.tags.div({ class: "deck-empty-desc" }, "Concurrent tasks, background workers, and subagent trees appear here.")
    );
  }

  return _dom.tags.div(
    { class: "jobs-panel" },
    _dom.each.call(void 0, _store.jobs, (job) =>
      _dom.tags.div(
        { class: `job-card status-${job.status}` },
        _dom.tags.div(
          { class: "job-card-hdr" },
          _dom.tags.span({ class: "job-status-dot" }),
          _dom.tags.span({ class: "job-name" }, job.name),
          job.role ? _dom.tags.span({ class: "job-role" }, job.role) : null,
          _dom.tags.span({ class: "job-status-pill" }, job.status.toUpperCase())
        ),
        job.summary
          ? _dom.tags.div({ class: "job-summary" }, job.summary)
          : null
      )
    )
  );
}

// 4. Files 面板
function renderFilesPanel() {
  const filter = _signal.signal("");
  const selectedFile = _signal.signal(null);

  const filtered = () => {
    const q = filter().toLowerCase().trim();
    const list = _store.files.call(void 0, );
    if (!q) return list;
    return list.filter((f) => f.path.toLowerCase().includes(q));
  };

  return _dom.tags.div(
    { class: "files-panel" },
    // 检索条
    _dom.tags.div(
      { class: "files-search-bar" },
      _dom.tags.input({
        class: "files-search-input",
        placeholder: "Search workspace files...",
        value: () => filter(),
        oninput: (e) => filter.set((e.target ).value),
      }),
      _dom.tags.button(
        {
          class: "files-refresh-btn",
          title: "Refresh files",
          onclick: () => _store.loadFiles.call(void 0, ),
        },
        "⟳"
      )
    ),

    // 文件列表与预览
    _dom.tags.div(
      { class: "files-split" },
      _dom.tags.div(
        { class: "files-tree" },
        _dom.each.call(void 0, filtered, (item) =>
          _dom.tags.div(
            {
              class: () =>
                `file-tree-item ${item.dir ? "is-dir" : "is-file"} ${selectedFile() && selectedFile().path === item.path ? "is-active" : ""}`,
              onclick: async () => {
                if (item.dir) return;
                try {
                  const res = await _net.apiFetch.call(void 0, `/api/file?path=${encodeURIComponent(item.path)}`);
                  if (res && res.text != null) {
                    selectedFile.set({ path: item.path, text: res.text });
                  }
                } catch (e) {
                  console.error(e);
                }
              },
            },
            _dom.tags.span({ class: "item-icon" }, item.dir ? "📁" : "📄"),
            _dom.tags.span({ class: "item-name" }, item.name)
          )
        )
      ),
      // 文件预览
      _dom.tags.div(
        { class: "file-preview-wrap" },
        () => {
          const cur = selectedFile();
          if (!cur) {
            return _dom.tags.div({ class: "file-preview-empty" }, "Select a file to inspect content.");
          }
          return _dom.tags.div(
            { class: "file-preview" },
            _dom.tags.div({ class: "file-preview-hdr" }, cur.path),
            _dom.tags.pre({ class: "file-preview-code" }, cur.text)
          );
        }
      )
    )
  );
}

};
__modules["splitter"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// splitter.ts —— 可拖拽双栏分隔调节器
var _dom = require('./dom');
var _signal = require('./signal');
var _store = require('./store');

const STORAGE_KEY = "piz.deckWidth";
const initialWidth = (() => {
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    return v ? parseInt(v, 10) : 520;
  } catch (_) {
    return 520;
  }
})();

 const deckWidth = _signal.signal(initialWidth); exports.deckWidth = deckWidth;

 function renderSplitter() {
  let isDragging = false;
  let startX = 0;
  let startW = 0;

  function onMouseDown(e) {
    if (!_store.deckOpen.call(void 0, )) return;
    isDragging = true;
    startX = e.clientX;
    startW = exports.deckWidth.call(void 0, );
    document.body.classList.add("is-resizing");

    window.addEventListener("mousemove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
  }

  function onMouseMove(e) {
    if (!isDragging) return;
    const delta = startX - e.clientX;
    const nextW = Math.max(320, Math.min(window.innerWidth * 0.75, startW + delta));
    exports.deckWidth.set(nextW);
  }

  function onMouseUp() {
    if (!isDragging) return;
    isDragging = false;
    document.body.classList.remove("is-resizing");
    try {
      localStorage.setItem(STORAGE_KEY, String(exports.deckWidth.call(void 0, )));
    } catch (_) {}
    window.removeEventListener("mousemove", onMouseMove);
    window.removeEventListener("mouseup", onMouseUp);
  }

  function onDblClick() {
    const defaultW = Math.floor(window.innerWidth * 0.45);
    exports.deckWidth.set(defaultW);
    try {
      localStorage.setItem(STORAGE_KEY, String(defaultW));
    } catch (_) {}
  }

  return _dom.tags.div({
    class: () => `workbench-splitter ${_store.deckOpen.call(void 0, ) ? "" : "is-hidden"}`,
    onmousedown: onMouseDown,
    ondblclick: onDblClick,
    title: "Drag to resize workbench, double-click to reset",
  });
} exports.renderSplitter = renderSplitter;

};
__modules["modal"] = function(module, exports, require) {
"use strict";Object.defineProperty(exports, "__esModule", {value: true});// modal.ts —— 权限审批弹窗、命令面板与设置弹窗
var _dom = require('./dom');















var _store = require('./store');
var _net = require('./net');
var _signal = require('./signal');

 function renderModals() {
  const container = _dom.tags.div({ class: "modals-layer" });

  // 1. 权限审批弹窗
  container.appendChild(
    _dom.tags.div(
      {
        class: () =>
          `modal-backdrop ${_store.pendingApproval.call(void 0, ) ? "is-visible" : "is-hidden"}`,
      },
      () => {
        const req = _store.pendingApproval.call(void 0, );
        if (!req) return null;

        return _dom.tags.div(
          { class: "modal-card permission-modal" },
          _dom.tags.div(
            { class: "modal-hdr" },
            _dom.tags.span({ class: "perm-icon" }, "🛡"),
            _dom.tags.h3({ class: "modal-title" }, "Permission Approval Required")
          ),
          _dom.tags.div(
            { class: "modal-body" },
            _dom.tags.p({ class: "perm-desc" }, req.desc || "The agent is requesting authorization for the following action:"),
            req.command
              ? _dom.tags.pre({ class: "perm-command" }, req.command)
              : null,
            req.path
              ? _dom.tags.div({ class: "perm-path" }, `Target: ${req.path}`)
              : null
          ),
          _dom.tags.div(
            { class: "modal-actions" },
            _dom.tags.button(
              {
                class: "btn btn-deny",
                onclick: () => _store.approve.call(void 0, req.id, false),
              },
              "Deny"
            ),
            _dom.tags.button(
              {
                class: "btn btn-allow",
                onclick: () => _store.approve.call(void 0, req.id, true),
              },
              "Allow Execution"
            )
          )
        );
      }
    )
  );

  // 2. Command Palette (Ctrl+K)
  const cmdQuery = _signal.signal("");
  container.appendChild(
    _dom.tags.div(
      {
        class: () =>
          `modal-backdrop ${_store.showSearchModal.call(void 0, ) ? "is-visible" : "is-hidden"}`,
        onclick: (e) => {
          if (e.target === e.currentTarget) _store.showSearchModal.set(false);
        },
      },
      () => {
        if (!_store.showSearchModal.call(void 0, )) return null;

        const q = cmdQuery().toLowerCase().trim();
        const sessionMatches = _store.sessions.call(void 0, ).filter((s) =>
          (s.title || s.name).toLowerCase().includes(q)
        );

        return _dom.tags.div(
          { class: "modal-card command-palette" },
          _dom.tags.div(
            { class: "palette-input-box" },
            _dom.tags.span({ class: "palette-icon" }, "⌕"),
            _dom.tags.input({
              class: "palette-input",
              placeholder: "Type a command or search sessions...",
              autofocus: true,
              value: () => cmdQuery(),
              oninput: (e) => cmdQuery.set((e.target ).value),
              onkeydown: (e) => {
                if (e.key === "Escape") _store.showSearchModal.set(false);
              },
            })
          ),
          _dom.tags.div(
            { class: "palette-list" },
            // 动作
            _dom.tags.div({ class: "palette-group-hdr" }, "Actions"),
            _dom.tags.div(
              {
                class: "palette-item",
                onclick: () => {
                  _store.createSession.call(void 0, );
                  _store.showSearchModal.set(false);
                },
              },
              _dom.tags.span({ class: "palette-item-icon" }, "＋"),
              _dom.tags.span({}, "Create New Session")
            ),
            _dom.tags.div(
              {
                class: "palette-item",
                onclick: () => {
                  _store.setDeckTab.call(void 0, "diffs");
                  _store.showSearchModal.set(false);
                },
              },
              _dom.tags.span({ class: "palette-item-icon" }, "⌥"),
              _dom.tags.span({}, "View Code Diffs")
            ),
            _dom.tags.div(
              {
                class: "palette-item",
                onclick: () => {
                  _store.setDeckTab.call(void 0, "terminal");
                  _store.showSearchModal.set(false);
                },
              },
              _dom.tags.span({ class: "palette-item-icon" }, "⌨"),
              _dom.tags.span({}, "Open Terminal Viewer")
            ),
            // 会话列表匹配
            sessionMatches.length > 0
              ? _dom.tags.div({ class: "palette-group-hdr" }, "Sessions")
              : null,
            sessionMatches.slice(0, 8).map((s) =>
              _dom.tags.div(
                {
                  class: "palette-item",
                  onclick: () => {
                    _store.switchSession.call(void 0, s.id);
                    _store.showSearchModal.set(false);
                  },
                },
                _dom.tags.span({ class: "palette-item-icon" }, "💬"),
                _dom.tags.span({ class: "palette-item-title" }, s.title || s.name),
                _dom.tags.span({ class: "palette-item-badge" }, `${s.messageCount} msgs`)
              )
            )
          )
        );
      }
    )
  );

  // 3. Auth Modal
  const inputTok = _signal.signal(_net.getToken.call(void 0, ));
  container.appendChild(
    _dom.tags.div(
      {
        class: () =>
          `modal-backdrop ${_store.showAuthModal.call(void 0, ) ? "is-visible" : "is-hidden"}`,
      },
      () => {
        if (!_store.showAuthModal.call(void 0, )) return null;

        return _dom.tags.div(
          { class: "modal-card auth-modal" },
          _dom.tags.h3({ class: "modal-title" }, "Authentication Required"),
          _dom.tags.p({ class: "auth-desc" }, "Please enter your server token to access piz."),
          _dom.tags.input({
            type: "password",
            class: "auth-token-input",
            placeholder: "Enter token...",
            value: () => inputTok(),
            oninput: (e) => inputTok.set((e.target ).value),
          }),
          _dom.tags.div(
            { class: "modal-actions" },
            _dom.tags.button(
              {
                class: "btn btn-primary",
                onclick: () => {
                  const t = inputTok().trim();
                  if (t) {
                    _net.setToken.call(void 0, t);
                    _store.showAuthModal.set(false);
                    window.location.reload();
                  }
                },
              },
              "Connect"
            )
          )
        );
      }
    )
  );

  // 4. Settings Modal
  container.appendChild(
    _dom.tags.div(
      {
        class: () =>
          `modal-backdrop ${_store.showSettingsModal.call(void 0, ) ? "is-visible" : "is-hidden"}`,
        onclick: (e) => {
          if (e.target === e.currentTarget) _store.showSettingsModal.set(false);
        },
      },
      () => {
        if (!_store.showSettingsModal.call(void 0, )) return null;

        return _dom.tags.div(
          { class: "modal-card settings-modal" },
          _dom.tags.div(
            { class: "modal-hdr" },
            _dom.tags.h3({ class: "modal-title" }, "Workspace Settings"),
            _dom.tags.button(
              {
                class: "modal-close-btn",
                onclick: () => _store.showSettingsModal.set(false),
              },
              "✕"
            )
          ),
          _dom.tags.div(
            { class: "modal-body" },
            _dom.tags.div(
              { class: "settings-row" },
              _dom.tags.label({}, "Active Model"),
              _dom.tags.select(
                {
                  class: "settings-select",
                  value: () => _store.model.call(void 0, ),
                  onchange: (e) => _store.switchModel.call(void 0, (e.target ).value),
                },
                _store.models.call(void 0, ).map((m) => _dom.tags.option({ value: m, selected: m === _store.model.call(void 0, ) }, m))
              )
            ),
            _dom.tags.div(
              { class: "settings-row" },
              _dom.tags.label({}, "Context Window Usage"),
              _dom.tags.div({ class: "settings-stat" }, `${_store.pct.call(void 0, )}% utilized`)
            ),
            _dom.tags.div(
              { class: "settings-row" },
              _dom.tags.label({}, "Interface Architecture"),
              _dom.tags.div({ class: "settings-stat" }, "WebUI Next v2.0 (Signals Reactive)")
            )
          )
        );
      }
    )
  );

  return container;
} exports.renderModals = renderModals;

};
__modules["main"] = function(module, exports, require) {
"use strict";// main.ts —— WebUI Next 根入口总装
var _dom = require('./dom');
var _topbar = require('./topbar');
var _sidebar = require('./sidebar');
var _chat = require('./chat');
var _composer = require('./composer');
var _deck = require('./deck');
var _splitter = require('./splitter');
var _modal = require('./modal');










var _store = require('./store');

function createApp() {
  const root = _dom.tags.div({ class: "app-root" });

  // 1. 顶栏
  root.appendChild(_topbar.renderTopBar.call(void 0, ));

  // 2. 主体三栏工作区容器 (Sidebar + Chat Area + Splitter + Deck)
  const mainWorkspace = _dom.tags.div(
    { class: "main-workspace" },
    // 左侧边栏
    _sidebar.renderSidebar.call(void 0, ),

    // 中央会话流与输入台
    _dom.tags.main(
      { class: "chat-main-column" },
      _chat.renderChatStream.call(void 0, ),
      _composer.renderComposer.call(void 0, )
    ),

    // 双栏调节中缝
    _splitter.renderSplitter.call(void 0, ),

    // 右侧工作台检视 Deck
    _deck.renderDeck.call(void 0, )
  );

  // 动态同步 Deck 宽度样式
  _splitter.deckWidth.subscribe((w) => {
    if (_store.deckOpen.call(void 0, )) {
      mainWorkspace.style.setProperty("--deck-width", `${w}px`);
    }
  });

  root.appendChild(mainWorkspace);

  // 3. 模态层
  root.appendChild(_modal.renderModals.call(void 0, ));

  return root;
}

// 键盘快捷键
function setupKeybindings() {
  window.addEventListener("keydown", (e) => {
    const isMeta = e.metaKey || e.ctrlKey;

    if (isMeta && e.key === "k") {
      e.preventDefault();
      _store.showSearchModal.update((v) => !v);
    } else if (isMeta && e.key === "b") {
      e.preventDefault();
      _store.toggleSidebar.call(void 0, );
    } else if (isMeta && e.key === "j") {
      e.preventDefault();
      _store.toggleDeck.call(void 0, );
    } else if (isMeta && e.shiftKey && (e.key === "D" || e.key === "d")) {
      e.preventDefault();
      _store.setDeckTab.call(void 0, "diffs");
    } else if (isMeta && e.shiftKey && (e.key === "T" || e.key === "t")) {
      e.preventDefault();
      _store.setDeckTab.call(void 0, "terminal");
    } else if (e.key === "Escape") {
      if (_store.showSearchModal.call(void 0, )) {
        _store.showSearchModal.set(false);
      } else if (_store.isStreaming.call(void 0, )) {
        _store.interrupt.call(void 0, );
      }
    }
  });
}

// 启动挂载
function mount() {
  const mountPoint = document.getElementById("app") || document.body;
  mountPoint.innerHTML = "";
  mountPoint.appendChild(createApp());

  setupKeybindings();
  _store.boot.call(void 0, );
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", mount);
} else {
  mount();
}

};
__req("main");
